### ISSUE TITLE
OutlineFilter unexpected behavior in Safari

### ISSUE THREAD

**Issue by nikkop** [pixijs/pixi-filters#107]
In Safari* there seems to be an issue with the OutlineFilter as it's behaving more like a drop shadow than an outline.

Safari - unexpected behavior
![safari-outlinefilter](https://user-images.githubusercontent.com/6517126/33886202-08b7f748-df46-11e7-9fe0-c4add01bd46f.jpg)

Chrome - expected behavior
![chrome-outlinefilter](https://user-images.githubusercontent.com/6517126/33886213-168ed1d4-df46-11e7-8855-a5f282df9e8d.jpg)

What could be causing this? Is there any quick fix for this?

*Was tested on Safari (Version 11.0.2 (13604.4.7.1.3)) on macOs

Thanks in advance

**Comment by finscn** [comment]
I can't  reproduce this issue  on Safari (Version 11.0.2 (13604.4.7.1.3)) on macOS (10.3.2).
My mac book is  : MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by nikkop** [comment]
@finscn This happened on:
Macbook Pro (Retina 13-inch, early 2015)
macOS 10.13.2 High Sierra

**Comment by finscn** [comment]
I've already tried to fix this bug.
Could you retest again with the last version ?

**Comment by nikkop** [comment]
@finscn Thank you for helping out.

Unfortunately it's still the same bug. Seems to be present on Safari 9, 10 and 11 on macOS.

**Comment by finscn** [comment]
Yes, I read GlowFilter ,  and the PR is inspired by GlowFilter. 
Are you sure you checkout the last version pixi-filters from github ? (& clear browser's cache)

**Comment by nikkop** [comment]
@finscn Yes, latest version (v2.4.1) and everything clean and fresh, nothing cached.
Do you have any idea what it might be? Due to that GlowFilter works I feel we can get the OutlineFilter to work as well! :)

**Comment by finscn** [comment]
Do you check http://pixijs.io/pixi-filters/tools/demo/ ?

**Comment by nikkop** [comment]
@finscn Yes I checked both the official demo (the one you linked) and locally in my own application and environment. Same issue still :(

**Comment by finscn** [comment]
@nikkop , do you know how to build pixi-filters by yourself ? 
Could you update `outline.frag` with these codes : 
```
varying vec2 vTextureCoord;
uniform sampler2D uSampler;

uniform vec2 thickness;
uniform vec4 outlineColor;
uniform vec4 filterClamp;

const float DOUBLE_PI = 3.14159265358979323846264 * 2.;

void main(void) {
    vec4 ownColor = texture2D(uSampler, vTextureCoord);
    vec4 curColor;
    float maxAlpha = 0.;
    vec2 displaced;
    for (float angle = 0.; angle <= DOUBLE_PI; angle += ${angleStep} ) {
        displaced.x = vTextureCoord.x + thickness.x * cos(angle);
        displaced.y = vTextureCoord.y + thickness.y * sin(angle);
        curColor = texture2D(uSampler, clamp(displaced, filterClamp.xy, filterClamp.zw));
        maxAlpha = max(maxAlpha, curColor.a);
    }
    float resultAlpha = max(maxAlpha, ownColor.a);
    gl_FragColor = vec4((ownColor.rgb + outlineColor.rgb * (1. - ownColor.a)) * resultAlpha, resultAlpha);
}
```

Then build pixi-filters , and test again ?

**Comment by nikkop** [comment]
@finscn Thanks for the suggestion.

I will have to wait until tomorrow because I don't have the Mac at home. I'll build it tomorrow and update you here how it went. Thanks!

**Comment by finscn** [comment]
@nikkop  , another thing . please visit http://webglreport.com  then post the result.
I want to know why on my macbook pro , there is no this issues.

**Comment by ivanpopelyshev** [comment]
try to decrease the quality.

**Comment by nikkop** [comment]
@finscn It worked! Simply checking `angle <= DOUBLE_PI` instead of `angle < DOUBLE_PI` fixed the issue. 
I can confirm it works in my case, so a PR of this would probably be appreciated. Great job!

**Comment by finscn** [comment]
@nikkop , thanks.
But I still want know the result of http://webglreport.com  on your macOS safari.

**Comment by nikkop** [comment]
@finscn Sure. I couldn't find any way to export the data so I took screenshots. Hope that's okay!

![webgl](https://user-images.githubusercontent.com/6517126/34521065-0a8f79ea-f08c-11e7-9b12-41b93344a6b5.jpg)
![webgl2](https://user-images.githubusercontent.com/6517126/34521066-0ab686de-f08c-11e7-9a06-154dac7ff1d9.jpg)

**Comment by finscn** [comment]
Thank you very much.
I compared yours with mine .
The only difference is video card. Mine is ATI.

So many issues are related to hardware(or hardware driver) , so sad.

**Comment by finscn** [comment]
@nikkop  , don't forget to close this one. thanks
