### ISSUE TITLE
Error while npm run build

### ISSUE THREAD

**Issue by naveencl** [pixijs/pixi-filters#108]
Hi, I have below error while "npm run build", please help me out in this.

npm run build -- --scope "{@pixi/filter-glow}"

> @ prebuild /Users/bcmacmini/pixi-filters
> npm run lint

> @ lint /Users/bcmacmini/pixi-filters
> eslint scripts **/src **/rollup.config.js --fix

> @ build /Users/bcmacmini/pixi-filters
> lerna run build "--scope" "{@pixi/filter-glow}"

lerna info version 2.5.1
lerna info scope {@pixi/filter-glow}
lerna ERR! EPACKAGES Errored while collecting packages and package graph
lerna ERR! Error: No packages found that match scope '{@pixi/filter-glow}'
lerna ERR!     at Function.filterPackages (/Users/bcmacmini/.nvm/versions/node/v4.8.4/lib/node_modules/lerna/lib/PackageUtilities.js:217:17)
lerna ERR!     at RunCommand.runPreparations (/Users/bcmacmini/.nvm/versions/node/v4.8.4/lib/node_modules/lerna/lib/Command.js:326:60)
lerna ERR!     at /Users/bcmacmini/.nvm/versions/node/v4.8.4/lib/node_modules/lerna/lib/Command.js:225:18
lerna ERR!     at RunCommand.run (/Users/bcmacmini/.nvm/versions/node/v4.8.4/lib/node_modules/lerna/lib/Command.js:212:14)
lerna ERR!     at Object.handler (/Users/bcmacmini/.nvm/versions/node/v4.8.4/lib/node_modules/lerna/lib/commands/RunCommand.js:45:88)
lerna ERR!     at Object.self.runCommand (/Users/bcmacmini/.nvm/versions/node/v4.8.4/lib/node_modules/lerna/node_modules/yargs/lib/command.js:233:22)
lerna ERR!     at Object.Yargs.self._parseArgs (/Users/bcmacmini/.nvm/versions/node/v4.8.4/lib/node_modules/lerna/node_modules/yargs/yargs.js:990:30)
lerna ERR!     at Object.Yargs.self.parse (/Users/bcmacmini/.nvm/versions/node/v4.8.4/lib/node_modules/lerna/node_modules/yargs/yargs.js:532:23)
lerna ERR!     at Object.<anonymous> (/Users/bcmacmini/.nvm/versions/node/v4.8.4/lib/node_modules/lerna/bin/lerna.js:4:25)

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/bcmacmini/.nvm/versions/node/v4.8.4/bin/node" "/Users/bcmacmini/.nvm/versions/node/v4.8.4/bin/npm" "run" "build" "--" "--scope" "{@pixi/filter-glow}"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! @ build: `lerna run build "--scope" "{@pixi/filter-glow}"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'lerna run build "--scope" "{@pixi/filter-glow}"'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna run build "--scope" "{@pixi/filter-glow}"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bcmacmini/pixi-filters/npm-debug.log

**Comment by bigtimebuddy** [comment]
Just don’t set a scope, “npm run build” is fine.

**Comment by naveencl** [comment]
Thank you. If I do “npm run build” also, I'm getting below errors,

npm run build

> @ prebuild /Users/bcmacmini/.Trash/pixi-filters 7.26.30 PM
> npm run lint


> @ lint /Users/bcmacmini/.Trash/pixi-filters 7.26.30 PM
> eslint scripts **/src **/rollup.config.js --fix


> @ build /Users/bcmacmini/.Trash/pixi-filters 7.26.30 PM
> lerna run build

lerna info version 2.5.1
lerna ERR! build Errored while running script in '@pixi/filter-bloom'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run build
lerna ERR! sh: rollup: command not found
lerna ERR! 
lerna ERR! npm ERR! Darwin 16.4.0
lerna ERR! npm ERR! argv "/Users/bcmacmini/.nvm/versions/node/v4.8.4/bin/node" "/Users/bcmacmini/.nvm/versions/node/v4.8.4/bin/npm" "run" "build:umd"
lerna ERR! npm ERR! node v4.8.4
lerna ERR! npm ERR! npm  v2.15.11
lerna ERR! npm ERR! file sh
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno ENOENT
lerna ERR! npm ERR! syscall spawn
lerna ERR! npm ERR! @pixi/filter-bloom@2.0.0 build:umd: `rollup -c -f umd && rollup -cp -f umd`
lerna ERR! npm ERR! spawn ENOENT
lerna ERR! npm ERR! 
lerna ERR! npm ERR! Failed at the @pixi/filter-bloom@2.0.0 build:umd script 'rollup -c -f umd && rollup -cp -f umd'.
lerna ERR! npm ERR! This is most likely a problem with the @pixi/filter-bloom package,
lerna ERR! npm ERR! not with npm itself.
lerna ERR! npm ERR! Tell the author that this fails on your system:
lerna ERR! npm ERR!     rollup -c -f umd && rollup -cp -f umd
lerna ERR! npm ERR! You can get information on how to open an issue for this project with:
lerna ERR! npm ERR!     npm bugs @pixi/filter-bloom
lerna ERR! npm ERR! Or if that isn't available, you can get their info via:
lerna ERR! npm ERR! 
lerna ERR! npm ERR!     npm owner ls @pixi/filter-bloom
lerna ERR! npm ERR! There is likely additional logging output above.
lerna ERR! 
lerna ERR! npm ERR! Please include the following file with any support request:
lerna ERR! npm ERR!     /Users/bcmacmini/.Trash/pixi-filters 7.26.30 PM/filters/bloom/npm-debug.log
lerna ERR! 
lerna ERR! npm ERR! Darwin 16.4.0
lerna ERR! npm ERR! argv "/Users/bcmacmini/.nvm/versions/node/v4.8.4/bin/node" "/Users/bcmacmini/.nvm/versions/node/v4.8.4/bin/npm" "run" "build"
lerna ERR! npm ERR! node v4.8.4
lerna ERR! npm ERR! npm  v2.15.11
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! @pixi/filter-bloom@2.0.0 build: `npm run build:umd && npm run build:es`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR! 
lerna ERR! npm ERR! Failed at the @pixi/filter-bloom@2.0.0 build script 'npm run build:umd && npm run build:es'.
lerna ERR! npm ERR! This is most likely a problem with the @pixi/filter-bloom package,
lerna ERR! npm ERR! not with npm itself.
lerna ERR! npm ERR! Tell the author that this fails on your system:
lerna ERR! npm ERR!     npm run build:umd && npm run build:es
lerna ERR! npm ERR! You can get information on how to open an issue for this project with:
lerna ERR! npm ERR!     npm bugs @pixi/filter-bloom
lerna ERR! npm ERR! Or if that isn't available, you can get their info via:
lerna ERR! npm ERR! 
lerna ERR! npm ERR!     npm owner ls @pixi/filter-bloom
lerna ERR! npm ERR! There is likely additional logging output above.
lerna ERR! 
lerna ERR! npm ERR! Please include the following file with any support request:
lerna ERR! npm ERR!     /Users/bcmacmini/.Trash/pixi-filters 7.26.30 PM/filters/bloom/npm-debug.log
lerna ERR! 
lerna ERR! > @pixi/filter-bloom@2.0.0 build /Users/bcmacmini/.Trash/pixi-filters 7.26.30 PM/filters/bloom
lerna ERR! > npm run build:umd && npm run build:es
lerna ERR! 
lerna ERR! 
lerna ERR! > @pixi/filter-bloom@2.0.0 build:umd /Users/bcmacmini/.Trash/pixi-filters 7.26.30 PM/filters/bloom
lerna ERR! > rollup -c -f umd && rollup -cp -f umd
lerna ERR! 
lerna ERR! 
lerna ERR!     at /Users/bcmacmini/.nvm/versions/node/v4.8.4/lib/node_modules/lerna/node_modules/execa/index.js:236:11
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
lerna ERR! build Errored while running script in '@pixi/filter-bulge-pinch'
lerna ERR! build Errored while running script in '@pixi/filter-ascii'
lerna ERR! build Errored while running script in '@pixi/filter-color-replace'

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/bcmacmini/.nvm/versions/node/v4.8.4/bin/node" "/Users/bcmacmini/.nvm/versions/node/v4.8.4/bin/npm" "run" "build"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! @ build: `lerna run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'lerna run build'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bcmacmini/.Trash/pixi-filters 7.26.30 PM/npm-debug.log

**Comment by bigtimebuddy** [comment]
Oh yah, I think I see the problem. Try NodeJS v6+

**Comment by naveencl** [comment]
I still have above errors after upgrading the NodeJS. The version of NodeJS is "9.2.1".

**Comment by bigtimebuddy** [comment]
Can you try running npm install again? Or “npm run bootstrap”

**Comment by naveencl** [comment]
It installed all dependencies, but still getting the error.

lerna info version 2.5.1
lerna info Bootstrapping 26 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished installing in root
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna success Bootstrapped 26 packages
@pixi/jsdoc-template@2.3.0 node_modules/@pixi/jsdoc-template
├── taffydb@2.7.3
└── underscore@1.8.3

rimraf@2.6.2 node_modules/rimraf
└── glob@7.1.2 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.6, minimatch@3.0.4)

http-server@0.9.0 node_modules/http-server
├── opener@1.4.3
├── corser@2.0.1
├── colors@1.0.3
├── http-proxy@1.16.2 (eventemitter3@1.2.0, requires-port@1.0.0)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── ecstatic@1.4.1 (url-join@1.1.0, he@0.5.0, mime@1.6.0, minimist@1.2.0)
├── union@0.4.6 (qs@2.3.3)
└── portfinder@0.4.0 (async@0.9.0, mkdirp@0.5.1)

gh-pages@0.11.0 node_modules/gh-pages
├── graceful-fs@4.1.2
├── q@1.4.1
├── async@1.5.2
├── wrench@1.5.8
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── globby@4.1.0 (arrify@1.0.1, object-assign@4.1.1, pify@2.3.0, array-union@1.0.2, pinkie-promise@2.0.1, glob@6.0.4)
└── q-io@1.13.2 (mimeparse@0.1.4, url2@0.0.0, mime@1.6.0, qs@1.2.2, collections@0.2.2)

jsdoc@3.5.5 node_modules/jsdoc
├── taffydb@2.6.2
├── escape-string-regexp@1.0.5
├── strip-json-comments@2.0.1
├── underscore@1.8.3
├── babylon@7.0.0-beta.19
├── marked@0.3.7
├── klaw@2.0.0 (graceful-fs@4.1.11)
├── requizzle@0.2.1 (underscore@1.6.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── bluebird@3.5.1
├── js2xmlparser@3.0.0 (xmlcreate@1.0.2)
└── catharsis@0.8.9 (underscore-contrib@0.3.0)

lerna@2.5.1 node_modules/lerna
├── p-finally@1.0.0
├── path-exists@3.0.0
├── get-port@3.2.0
├── dedent@0.7.0
├── read-cmd-shim@1.0.1
├── signal-exit@3.0.2
├── hosted-git-info@2.5.0
├── safe-buffer@5.1.1
├── graceful-fs@4.1.11
├── async@1.5.2
├── semver@5.4.1
├── command-join@2.0.0
├── write-file-atomic@2.3.0 (imurmurhash@0.1.4)
├── is-ci@1.0.10 (ci-info@1.1.2)
├── globby@6.1.0 (object-assign@4.1.1, pify@2.3.0, pinkie-promise@2.0.1, array-union@1.0.2)
├── glob@7.1.2 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.6)
├── temp-write@3.3.0 (pify@2.3.0, temp-dir@1.0.0, is-stream@1.1.0, uuid@3.1.0, make-dir@1.1.0)
├── write-json-file@2.3.0 (detect-indent@5.0.0, pify@3.0.0, make-dir@1.1.0, sort-keys@2.0.0)
├── write-pkg@3.1.0 (sort-keys@2.0.0)
├── glob-parent@3.1.0 (path-dirname@1.0.2, is-glob@3.1.0)
├── minimatch@3.0.4 (brace-expansion@1.1.8)
├── find-up@2.1.0 (locate-path@2.0.0)
├── load-json-file@3.0.0 (pify@2.3.0, strip-bom@3.0.0, parse-json@3.0.0)
├── cmd-shim@2.0.2 (mkdirp@0.5.1)
├── chalk@2.3.0 (escape-string-regexp@1.0.5, supports-color@4.5.0, ansi-styles@3.2.0)
├── columnify@1.5.4 (strip-ansi@3.0.1, wcwidth@1.0.1)
├── execa@0.8.0 (strip-eof@1.0.0, is-stream@1.1.0, get-stream@3.0.0, npm-run-path@2.0.2, cross-spawn@5.1.0)
├── fs-extra@4.0.3 (universalify@0.1.1, jsonfile@4.0.0)
├── package-json@4.0.1 (got@6.7.1, registry-auth-token@3.3.1, registry-url@3.1.0)
├── read-pkg@2.0.0 (path-type@2.0.0, load-json-file@2.0.0, normalize-package-data@2.4.0)
├── npmlog@4.1.2 (set-blocking@2.0.0, console-control-strings@1.1.0, gauge@2.7.4, are-we-there-yet@1.1.4)
├── inquirer@3.3.0 (ansi-escapes@3.0.0, rx-lite-aggregates@4.0.8, cli-width@2.2.0, through@2.3.8, rx-lite@4.0.8, figures@2.0.0, mute-stream@0.0.7, strip-ansi@4.0.0, string-width@2.1.1, run-async@2.3.0, external-editor@2.1.0, cli-cursor@2.1.0)
├── conventional-recommended-bump@1.1.0 (object-assign@4.1.1, git-semver-tags@1.2.3, conventional-commits-filter@1.1.1, concat-stream@1.6.0, git-raw-commits@1.3.0, conventional-commits-parser@2.1.0, meow@3.7.0)
├── yargs@8.0.2 (decamelize@1.2.0, get-caller-file@1.0.2, set-blocking@2.0.0, read-pkg-up@2.0.0, camelcase@4.1.0, y18n@3.2.1, which-module@2.0.0, yargs-parser@7.0.0, require-main-filename@1.0.1, require-directory@2.1.1, string-width@2.1.1, cliui@3.2.0, os-locale@2.1.0)
├── strong-log-transformer@1.0.6 (byline@5.0.0, duplexer@0.1.1, through@2.3.8, minimist@0.1.0, moment@2.19.4)
├── conventional-changelog-cli@1.3.5 (add-stream@1.0.0, tempfile@1.1.1, meow@3.7.0, conventional-changelog@1.1.7)
└── lodash@4.17.4

eslint@4.13.1 node_modules/eslint
├── path-is-inside@1.0.2
├── strip-json-comments@2.0.1
├── imurmurhash@0.1.4
├── natural-compare@1.4.0
├── estraverse@4.2.0
├── is-resolvable@1.0.1
├── pluralize@7.0.0
├── ignore@3.3.7
├── globals@11.1.0
├── semver@5.4.1
├── esquery@1.0.0
├── functional-red-black-tree@1.0.1
├── esutils@2.0.2
├── progress@2.0.0
├── doctrine@2.0.2
├── text-table@0.2.0
├── json-stable-stringify-without-jsonify@1.0.1
├── strip-ansi@4.0.0 (ansi-regex@3.0.0)
├── cross-spawn@5.1.0 (shebang-command@1.2.0, lru-cache@4.1.1, which@1.3.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── levn@0.3.0 (type-check@0.3.2, prelude-ls@1.1.2)
├── minimatch@3.0.4 (brace-expansion@1.1.8)
├── glob@7.1.2 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0)
├── debug@3.1.0 (ms@2.0.0)
├── require-uncached@1.0.3 (resolve-from@1.0.1, caller-path@0.1.0)
├── concat-stream@1.6.0 (inherits@2.0.3, typedarray@0.0.6, readable-stream@2.3.3)
├── chalk@2.3.0 (escape-string-regexp@1.0.5, supports-color@4.5.0, ansi-styles@3.2.0)
├── optionator@0.8.2 (fast-levenshtein@2.0.6, type-check@0.3.2, wordwrap@1.0.0, deep-is@0.1.3, prelude-ls@1.1.2)
├── eslint-scope@3.7.1 (esrecurse@4.2.0)
├── babel-code-frame@6.26.0 (js-tokens@3.0.2, chalk@1.1.3)
├── table@4.0.2 (string-width@2.1.1, slice-ansi@1.0.0, ajv-keywords@2.1.1)
├── inquirer@3.3.0 (ansi-escapes@3.0.0, rx-lite-aggregates@4.0.8, cli-width@2.2.0, rx-lite@4.0.8, through@2.3.8, mute-stream@0.0.7, figures@2.0.0, string-width@2.1.1, run-async@2.3.0, external-editor@2.1.0, cli-cursor@2.1.0)
├── file-entry-cache@2.0.0 (object-assign@4.1.1, flat-cache@1.3.0)
├── js-yaml@3.10.0 (esprima@4.0.0, argparse@1.0.9)
├── ajv@5.5.1 (co@4.6.0, json-schema-traverse@0.3.1, fast-deep-equal@1.0.0, fast-json-stable-stringify@2.0.0)
├── espree@3.5.2 (acorn@5.2.1, acorn-jsx@3.0.1)
└── lodash@4.17.4

**Comment by bigtimebuddy** [comment]
The only other thing you could be that that your node_modules got borked. You could do a clean, nuke your modules, and start over.
```
npm run clean -- --yes
rm -rf node_modules
npm install
npm run build
```

**Comment by bigtimebuddy** [comment]
@naveencl did you solve this?

**Comment by naveencl** [comment]
No, I still have same errors.

**Comment by naveencl** [comment]
Got issue in npm run build on mac, 

```
** lerna run build

lerna info version 2.5.1
lerna ERR! build Errored while running script in '@pixi/filter-advanced-bloom'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run build
lerna ERR! Error: SyntaxError: Unexpected token {
lerna ERR! 
lerna ERR! 
lerna ERR! npm ERR! Darwin 16.4.0
lerna ERR! npm ERR! argv "/Users/bcmacmini/.nvm/versions/node/v4.8.4/bin/node" "/Users/bcmacmini/.nvm/versions/node/v4.8.4/bin/npm" "run" "build"
lerna ERR! npm ERR! node v4.8.4
lerna ERR! npm ERR! npm  v2.15.11
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! @pixi/filter-advanced-bloom@2.3.0 build: `rollup -cp && rollup -cp -f umd`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR! 
lerna ERR! npm ERR! Failed at the @pixi/filter-advanced-bloom@2.3.0 build script 'rollup -cp && rollup -cp -f umd'.
lerna ERR! npm ERR! This is most likely a problem with the @pixi/filter-advanced-bloom package,
lerna ERR! npm ERR! not with npm itself.
lerna ERR! npm ERR! Tell the author that this fails on your system:
lerna ERR! npm ERR!     rollup -cp && rollup -cp -f umd
lerna ERR! npm ERR! You can get information on how to open an issue for this project with:
lerna ERR! npm ERR!     npm bugs @pixi/filter-advanced-bloom
lerna ERR! npm ERR! Or if that isn't available, you can get their info via:
lerna ERR! npm ERR! 
lerna ERR! npm ERR!     npm owner ls @pixi/filter-advanced-bloom
lerna ERR! npm ERR! There is likely additional logging output above.
lerna ERR! 
lerna ERR! npm ERR! Please include the following file with any support request:
lerna ERR! npm ERR!     /Users/bcmacmini/NaveenPambi/components/pixi-filters/filters/advanced-bloom/npm-debug.log
lerna ERR! 
lerna ERR! > @pixi/filter-advanced-bloom@2.3.0 build /Users/bcmacmini/NaveenPambi/components/pixi-filters/filters/advanced-bloom
lerna ERR! > rollup -cp && rollup -cp -f umd
lerna ERR! 
lerna ERR! 
lerna ERR!     at /Users/bcmacmini/NaveenPambi/components/pixi-filters/node_modules/lerna/node_modules/execa/index.js:236:11
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
lerna ERR! build Errored while running script in '@pixi/filter-ascii'
lerna ERR! build Errored while running script in '@pixi/filter-bulge-pinch'
lerna ERR! build Errored while running script in '@pixi/filter-bloom'
**
```
On windows it runs fine.

**Comment by bigtimebuddy** [comment]
NodeJS has to be 6+, try again with a different version. Also please pull the latest

**Comment by naveencl** [comment]
It is working now, with the latest v2.4.0. Thanks a lot!

**Comment by bigtimebuddy** [comment]
Cool, glad you figured it out
