### ISSUE TITLE
where is the bin folder ?

### ISSUE THREAD

**Issue by antag0n1st** [pixijs/pixi-filters#11]
Is there build for the filters ?

**Comment by maryisdead** [comment]
Agreed. It's a big turn-off when I have to jump through hoops to get working code. Fwiw, you can grab a pre-built file from the demo: view-source:http://pixijs.github.io/pixi-filters/examples/

**Comment by englercj** [comment]
The bin folder is on the publish branch:

https://github.com/pixijs/pixi-filters/tree/publish/bin

No hoops required.

**Comment by maryisdead** [comment]
Ah, thanks, mate! Maybe a not in the README.md might help lost souls like us?
