### ISSUE TITLE
[Suggest]Can use `null` for default argument value (type is number).

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#115]
if I want to use default argument value , I  have to use: 
```
new XxxxFilter( first,  undefined,  third);
```

If I use 
```
new XxxxFilter( first,  null,  third);
```
the second will be `null`.

I know `undefined` & `null` are different ,  and I agree with `use undefined for default value`.

But for number-argument , I hope I also could use `null for default value`.

**Comment by bigtimebuddy** [comment]
I think this is a case of bad API design. If a use-case is to not set the second argument would either consider making it last or use `options` Object instead.
