### ISSUE TITLE
blendMode not support with filters?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-filters#120]
hi friend,  its normal all filters not support blendMode ??
i add filter on pixi Container, and i try add blendMode on children or parent.
children are spriteAnimation.

```javascript
F = new PIXI.filters.OutlineFilter (10, 0x000000)
pixiSSA._animationControler._events[5].filters = [F];
pixiSSA._animationControler._events[5].children[0].blendMode = 2; // AnimatedSprite
// also try on parents
pixiSSA._animationControler._events[5].parent.blendMode = 2; // Sprite
```

thank a lot for you awsome work

**Comment by ivanpopelyshev** [comment]
Filter uses separate framebuffer (layer) to render on. Thus, your sprite is blended with transparent background of that layer and not background of your stage.

However, you can apply blendmode to that framebuffer:

```js
f.blendMode = 2;
```

**Comment by djmisterjon** [comment]
Hey thank a lot for your help.
what your say seems logical to me.
