### ISSUE TITLE
[SUGGESTION] Rename the dist js file

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#128]
in other pixi project , the  `name.js` is a  non-compact & non-obfuscated file.

the `name.min.hs` is compact & obfuscated file.

I hope pixi-filter could be the same style .

I don't know anything about build-script , so I can't create a PR for this suggestion.

**Comment by bigtimebuddy** [comment]
Thank you for the suggestion. I understand this is slightly different from **pixi.js** and other plugins.

For this project and for v5, I have decided to not generate a un-obfuscated file. Sourcemaps are well-supported and I do not find a compelling reason to generate both files. For the sake of simplicity, I'm going to keep the file naming as-is.

**Comment by finscn** [comment]
Hi @ivanpopelyshev  & @bigtimebuddy  , 
 in pixi-filters , you  only keep `obfuscated file` .
 in pixi-tilemap , you  only keep `un-obfuscated file` .

Whatever which style  is better , I think there should be only one style.
 I hope in the future ,  your views could be coincided.

Thanks.

**Comment by ivanpopelyshev** [comment]
I dont like obfuscation, and our build systems differ.

**Comment by finscn** [comment]
@bigtimebuddy  , in fact , I agree with @ivanpopelyshev .

the obfuscation is not  pixi core team's work .

How to obfuscate , use what tool to obfuscate , use what arguments of the tool , they are pixi users's work.


I know when submit the project to npm & cdn , we need a minimize file ,
But it's another standalone process,  not belong `build`.

**Comment by bigtimebuddy** [comment]
Part of the reason to obfuscate is because not every user uses a tool to build or concatenate. In fact, many users use `<script src=""></script>` includes on their HTML to import. Obfuscated code is more friendly for this use-case by keep sizes small and removing comments.

**Comment by finscn** [comment]
@bigtimebuddy  ,I understand your view.  But I think keep `un-obfuscated file` is useful.
Then user could decide `How to obfuscate , use what tool to obfuscate , use what arguments of the tool `
