### ISSUE TITLE
ColorMatrixFilter broken in Chrome

### ISSUE THREAD

**Issue by stephentt** [pixijs/pixi-filters#13]
Firefox version:  49.0.2
Chrome version: Version 54.0.2840.87 m

If you go to this page in both Firefox and Chrome and compare you can see the the ColorMatrixFilter has no effect.

https://pixijs.github.io/examples/#/filters/filter.js

I will include an image comparing the two where it is apparent where Firefox is on the left and Chrome is on the right.  I am using this filter heavily in my application so I would b very appreciative if it was fixed, thank you.

![colorizefilter_firefox_vs_chrome](https://cloud.githubusercontent.com/assets/7808960/19985870/dc06986a-a1d1-11e6-897c-3419551d39d6.png)

**Comment by bigtimebuddy** [comment]
@stephentt I'm unable to reproduce and I'm on Chrome 54.0.2840.98  on MacOS. Can anyone else repro?

**Comment by GoodBoyDigital** [comment]
Just tested here on my mac - running on here! @stephentt are you PC or Mac?

**Comment by stephentt** [comment]
I'm on PC.

**Comment by stephentt** [comment]
Just tried again with latest Chrome (Version 54.0.2840.99 m) and it still happens for me.  PC and Windows 7 64 bit.

**Comment by stephentt** [comment]
I just tried again today with Chrome (Version 55.0.2883.87 m) and the filter is working correctly now.
