### ISSUE TITLE
MotionBlurFilter & RadialBlurFilter  error at Samsumg S7

### ISSUE THREAD

**Issue by wwepenguin** [pixijs/pixi-filters#142]
i run pixi filter demo page  at samsung s7
enable MotionBlurFilter  or RadialBlurFilter  has some error on compiler fragShader program

error message is at chrome remote debugerr

compileProgram.js:73 0:7: S0012: Global variable initializer must be a constant expression
compileProgram.js:36 Pixi.js Error: Could not initialize shader.
compileProgram.js:37 gl.VALIDATE_STATUS false
compileProgram.js:38 gl.getError() 1281
Pixi.js Warning: gl.getProgramInfoLog() missing shaders
WebGL: INVALID_VALUE: getProgramParameter: no object or object deleted
extractUniforms.js:16 WebGL: INVALID_VALUE: getProgramParameter: no object or object deleted
Uncaught TypeError: Cannot read property 'location' of undefined
Uncaught TypeError: Cannot read property 'value' of undefined

**Comment by ivanpopelyshev** [comment]
IT possible that #140 Fixed it yesterday. Please re-build pixi-filters from sources and see if its fixed.

**Comment by wwepenguin** [comment]
i move all calculator expression  in to main function problem will fix 
just like : https://hub.jmonkeyengine.org/t/solved-fog-shader-filter-fails-on-android-samsung-galaxy-s7/35941/2

Will samsung s7 optimize fragment shader code  ?

**Comment by finscn** [comment]
@wwepenguin  , I'll fix it later. 
but I prefer to `move some calculators to js` than `move to main()`.
