### ISSUE TITLE
Problem with outline and drop-shadow filter interaction

### ISSUE THREAD

**Issue by meerfolk** [pixijs/pixi-filters#146]
When I try to add outline and drop-shadow filters to Text class using 
```txt.filters = [new OutlineFilter(2, 0xFF0000), new DropShadowFilter(90, 5, 1, 0x00FF00, 1)];```
all works fine, but when I use different order of filters
```txt.filters = [new DropShadowFilter(90, 5, 1, 0x00FF00, 1), new OutlineFilter(2, 0xFF0000)];```
drop-shadow filter doesn't work

**Comment by ivanpopelyshev** [comment]
Post a fiddle, save our time :) Or dont, and wait when I wont be that lazy like now (sunday evening)

**Comment by bigtimebuddy** [comment]
Also, just as an aside, Text already supports both dropshadow and stroke styling: http://pixijs.io/pixi-text-style/. Is there a ready why you want to use filters here?

**Comment by meerfolk** [comment]
Text it is only for example. In Text, beter to use it's own filters.

**Comment by bigtimebuddy** [comment]
Please provide a jsfiddle which demonstrates the bug.

**Comment by bigtimebuddy** [comment]
This seems to work fine. Closing this issue.
https://jsfiddle.net/bigtimebuddy/vamq5kLb/
