### ISSUE TITLE
Copy Code to ClipBoard or Console.Log

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-filters#147]
Hi guys, its possible to add a button for copy code in clipBoard or make a console.log when click on enable ?
sorry for the request, but I suffer from extreme laziness.
I find it long and tedious to experiment and test setup on a console.

example a small button like this can be very cool
![sans-titre-1](https://user-images.githubusercontent.com/24865815/36456364-936ddf84-1672-11e8-86e5-0b224d76aa06.jpg)
thanks

**Comment by bigtimebuddy** [comment]
Thanks for the suggestion, but I don't think the purpose of this demo is about creating production code, it's mostly about discovery and understand what the filters do. We need something that is similar to https://github.com/pixijs/pixi-text-style for generate usable code, but also where people can provide their own images. Many of these filters are clamped mostly to make the demo look good. A general purpose tool would be more flexible.

**Comment by djmisterjon** [comment]
@bigtimebuddy 
I was not talking about creating a production code, but mostly providing a basic code with the parameters chosen, to copy paste very quickly and to get a simple basis method and save some precious seconde.
But I  find an alternative with **vscode** and **intellisense** and ts.
So i include intellisense for some filters for my own workflow.
http://endlessillusoft.com/rpgmakermv-intellisense/

However it is worth that a clown of your tool existe for filters, would be wonderful.
As soon as I have to manipulate text I always go through your tools.
It save for me precious minutes.

But we can close, and maybe if one day a pixiGuy have time, this can be cool to have a tool to generate code. :)
