### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by Patrick-Hammond** [pixijs/pixi-filters#152]
I've been trying to add some custom filters and have it bundle correctly. The js output works correctly, but i'm unable to get the types.d.ts to include my custom typings.
Is the types.d.ts generated dynamically? i.e. a concatination of the typings in each filter.

**Comment by ivanpopelyshev** [comment]
Yes.

**Comment by Patrick-Hammond** [comment]
In that case i'm rather confused :)
If I make a change to, for example, filters/color-map/types.d.ts then I would expect to see it reflected in the bundle types.d.ts. after re-building which I don't.
Is there anything beyond **npm run build** that I should be doing?

**Comment by ivanpopelyshev** [comment]
Ok, lets see.. for example, this PR: https://github.com/pixijs/pixi-filters/pull/148/files
Both files are modified. 

There's no build, you have to add this thing in both places.

**Comment by Patrick-Hammond** [comment]
Okay, thanks for the clarification! I was just concerned I was doing something wrong. I'll copy it manually then.

**Comment by ivanpopelyshev** [comment]
Yep, I didnt know which system do we use in filters. I just finished draft for pixi-v5 typings and they are compatible with filter typings.

**Comment by bigtimebuddy** [comment]
These typings are hand rolled. You might want to check out the wiki for adding new filters.

**Comment by Patrick-Hammond** [comment]
Okay, didn't know about that page. Very helpful, thanks 👍
