### ISSUE TITLE
How to build with only select filters + One request for dummies

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi-filters#155]
I wonder how "bundle/dist/pixi-filters.js" could be built only including select filters, I tried the example commands on Readme.md but no luck, it just builds each filter in place, while `npm run build` builds all of them and combines them in "bundle/dist/pixi-filters.js"

It took me 15 minutes to figure out how to actually import the filters (ie. find out a pre-built js file), might be great to improve Readme.md to aid those who just want to import a pre-built .js file the old way - Just linking to https://github.com/pixijs/pixi-filters/releases could even do, the latest version doesn't have pre-built .js's, but older ones do

Edit: The examples could also be updated to link to the releases url, instead of the old project http://pixijs.io/examples/?v=v4.7.1#/filters/outline-filter.js

**Comment by bigtimebuddy** [comment]
There are two approach for including a custom set of filters.

## Individual Filter Bundling

If you are using a JavaScript bundler (Webpack, Rollup, Parcel, etc) to build your project, install the package for the individual filter. For instance:

```bash
npm i @pixi/filter-outline @pixi/filter-convolution -S
```

Then include these in your source-code:

```js
import '@pixi/filter-outline';
import '@pixi/filter-convolution';
```

## Direct Linking via CDN

If you aren't using a bundler, you can get a direct like to a build using something like **unpkg.com** or another CDN for NPM. For instance:

```html
<script src="https://unpkg.com/@pixi/filter-outline@2.6.0/lib/filter-outline.js"></script>
<script src="https://unpkg.com/@pixi/filter-convolution@2.6.0/lib/filter-convolution.js"></script>
```

 Currently, I do not include the individual builds in the Github releases, so you'll have to use another service to grab them. You could also use **jsdelivr.com**, example: https://www.jsdelivr.com/package/npm/@pixi/filter-outline


Hope that helps!
