### ISSUE TITLE
skew + OutlineFilter not work if pivot set to 0 ?!

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-filters#157]
if we leave pivot to 0 and add `skew  `+ **`OutlineFilter`** the Sprite disappear !
will work only if assign a pivot ? ex: `pivot.x = 0.01`
it's very embarrassing as a bug, especially in my context where my element disappears when I select them.
Any idea ?

**my current version**
 * pixi.js - v4.7.0
 * pixi-filters - v2.5.1
thank

**Comment by ivanpopelyshev** [comment]
try 4.7.1

**Comment by djmisterjon** [comment]
@ivanpopelyshev 
Am sorry it not seem to fix!
i made you a fast 1 min video to show you the bug.
When mouse hover , the sprite get the filter `OutlineFilter`.
When `pivot `assigned, and i use `skew`, it work fine.
But if i remove pivot , the obj sprite disappear literally when mouse hover, and i get also after a strange black screen from the filter `ColorMatrixFilter.desaturate `for the map!

[https://youtu.be/Dj2xPgIVO28](https://youtu.be/Dj2xPgIVO28)
I do not know if the video will help visualize the problem.

**Comment by djmisterjon** [comment]
I guess I'm the only one, I'll try to investigate on my side.

**Comment by ivanpopelyshev** [comment]
are you sure pivot is (0,0) if you dont set it? please make a fiddle if you can , I want to squash that bug

**Comment by djmisterjon** [comment]
@ok am making a jsfiddle for reproduce the bug.
Can you just tell me what the CDN for pixi **OutlineFilter**  ?

**Comment by djmisterjon** [comment]
i don't know how load filter https://jsfiddle.net/jonforum/L4mg1kht/13/
i get error !

**Comment by djmisterjon** [comment]
@ivanpopelyshev ho i find it.
iT so stupide, i add `line `for draw the distance pivot in children of sprite.
And pixi don't like line with 0,0 distance!
`line.moveTo(0,0).lineTo(sprite.pivot.x, sprite.pivot.y).endFill();`
Strangely pixi does not return an error!, but it gives INFINY to the bound when a filter is added.

I fix it for now with a minimum
```javascript
line.moveTo(0,0).lineTo(sprite.pivot.x||0.1, sprite.pivot.y).endFill();
sprite.addChild(line,text);
```
