### ISSUE TITLE
How to import pixi-filters in ES6?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#158]
When I use 
```
import * as PIXI from 'pixi.js'
```
to import pixi.js , 

How to import pixi-filters  ? 

I've tried 
```
import  'pixi-filters.js'
```
and 
```
require('pixi-filters.js')
```
,
both of them are failed.

**Comment by bigtimebuddy** [comment]
pixi-filters not pixi-filters.js

**Comment by finscn** [comment]
done with https://github.com/pixijs/pixi-filters/pull/160

**Comment by egogg** [comment]
still does not work
