### ISSUE TITLE
[REQUEST] MotionBlurFilter .velocity property is not PIXI.Point

### ISSUE THREAD

**Issue by AlexSorochinsky** [pixijs/pixi-filters#161]
Trying to use .velocity property to animate blur effect (start to move sprite - blur increased, stop to move sprite - blur decreased), but nothing worked. Looks like MotionBlurFilter do not have any reaction on .velocity.x and .velocity.y properties change.

I propose to fix it and use PIXI.Point here.

**Comment by ivanpopelyshev** [comment]
He means ObservablePoint :) I can make that PR later.

**Comment by bigtimebuddy** [comment]
Good suggestions @AlexSorochinsky. Feel free to make a PR @ivanpopelyshev, I will probably be creating a release as soon as you do that because there are a bunch of pending minor changes waiting to release.

**Comment by bigtimebuddy** [comment]
I created a PR for this. Was pretty straightforward.

**Comment by ivanpopelyshev** [comment]
Approved.
