### ISSUE TITLE
sun flare shader filter [suggest]

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-filters#163]
it would be great if we could have something similar to this to simulate a sun or start

https://shaderfrog.com/app/view/1981

**Comment by finscn** [comment]
I think pixi-filters should focus on `visual effect` , not `specific entity`.
 Except the entity should be created by shader , e.g.  rain , snow,  light, water-effect , starry-sky(not star).

**Comment by djmisterjon** [comment]
I am not really a specialist in filtering and fx, but if you take a look on the source code , the effect can be named **Turbulence fractal** maybe.
am trying to find.
I wanted to try to put a nice filter on my prototype, but I was not able to find a filter to simulate the desired effect.
From where my suggestion.
My only solution for now, is to make it inside AfterEffect to generate the desired filters, and render it in spriteAnimations.
But that increases the memory quite significantly, and especially does not allow as dynamic as a shader.

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/7mWX4WPGNeU/0.jpg)](https://youtu.be/7mWX4WPGNeU)
