### ISSUE TITLE
ShockwaveFilter not update correctly ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-filters#164]
hi guys , is it normal if a add a filter to a pixi sprite and after a change the pivot or the scale of this sprite, the ShockwaveFilter not follow the sprite ?
In my context , the sprites are the map with a parent container for diffuse and normal.
It look follow the stage screen but not the sprite assigned.
![5b06019460c54617196132](https://user-images.githubusercontent.com/24865815/40457502-cac9d70e-5ec4-11e8-92c3-a9b9e3a38a01.gif)

```javascript
_cases.prototype.onMousedown = function() {
    this.current._d.filters = [this.filter.OutlineFilter_case0];
    // create a Shockwave when click on map diffuse sprite
    SceneManager._scene._map.sprite_n.filters = [this.filter.ShockwaveFilter];
    // test config the ShockwaveFilter
    this.filter.ShockwaveFilter.center = [this.current.x, this.current.y]
    this.filter.ShockwaveFilter.time = 0;
    // test ShockwaveFilter update
    clearInterval(this.interval);
    let power = 1;
    this.interval = setInterval(function(){ 
        this.time+=0.001;
        power++>100 && (this.time+=this.time/40);
    }.bind(this.filter.ShockwaveFilter), 5);
};
```
I'm not sure if this is normal behavior or if I have to build an update manually to adjust its position and scale from is parent ?
thank

**Comment by ivanpopelyshev** [comment]
According to shader, this thing doesnt care about sprite coords. 

https://github.com/pixijs/pixi-filters/blob/master/filters/shockwave/src/shockwave.frag#L35

You have to change its coords manually.
