### ISSUE TITLE
Unable to yarn add filters.

### ISSUE THREAD

**Issue by rockmandash** [pixijs/pixi-filters#168]
Hello, sorry, I don't know if this is yarn's issue or pixi's issue.
After I run `yarn add @pixi/filter-motion-blur`

I have these result
```
yarn add v1.6.0
(node:39885) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/minBarWidthimatch/-/minBarWidthimatch-3.0.4.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/josephwang/Work/catchad-slider/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by englercj** [comment]
We don't use `Buffer` anywhere, it is possible some dependency does but as it happens before you even resolve packages, it is likely you are using an old version of yarn on a new version of node.

**Comment by englercj** [comment]
Looks like yarn is trying to get a dependency that doesn't exist. Not sure what to tell you here :/

We use npm and packages on npm. If there is something on npm, but not yarn it is possible that is causing the issue? yarn just isn't officially supported, I don't think there is anything we can do for you here. You'lkl have to trace it down more to find which dependencies in the tree are causing the issue.
