### ISSUE TITLE
RGB Filter, blue doen't mooves

### ISSUE THREAD

**Issue by JenGL** [pixijs/pixi-filters#17]
In the rgb split filter the blue doesn't moves at all :D 

https://jsfiddle.net/6w0kuqko/71/ -> in here I move red, bue and green and you can see red and green moving

https://jsfiddle.net/6w0kuqko/73/ -> in here i move only blue and set red and green to 0,0. Nothing is moving !

**Comment by JenGL** [comment]
GOT IT!: In the blue uniform getter you have an unnecessary .value !

@see: https://cdnjs.cloudflare.com/ajax/libs/pixi-filters/1.0.6/rgb.js

**Comment by JenGL** [comment]
created pull request with the fix

**Comment by bigtimebuddy** [comment]
Thanks for the fix.
