### ISSUE TITLE
AsciiFilter makes everything black on some Mac devices

### ISSUE THREAD

**Issue by nathanvogel** [pixijs/pixi-filters#173]
Hi, 

The whole view turns black when enabling the AsciiFilter on some Mac devices.
It can easily be tested on https://pixijs.io/pixi-filters/tools/demo/ 

### Results of my tests: 

Fails:
- Macbook Pro (15-inch, 2014)
- iMac (27-inch, Late 2013), 16 Go RAM, Nvidia GeForce GTX 780M 4096 Mo

Succeeds:
- Macbook Pro (15-inch, 2016), 16 Go RAM, Radeon Pro 450 2048 Mo, Intel HD Graphics 530 1536 Mo
- Windows 10 PC build (Nvidia GTX 770)
- LG G6, Android 8.0

The original shader on ShaderToy does the same: https://www.shadertoy.com/view/lssGDj

**Comment by movAX13h** [comment]
The shader can be optimized now that binary operations are available in GLES. 
I don't know if it will fix the problem on these devices but I guess it's worth a try.
I'll have a look later today. 
Thanks for reporting.

**Comment by nathanvogel** [comment]
Awesome, thanks!

**Comment by movAX13h** [comment]
I've noticed that the current implementation of my shader in PixiJs draws the characters upside down.

**Comment by nathanvogel** [comment]
No, sadly the Shadertoy view is still black :( At least on the iMac.

This console output is the same on both working and failing devices btw:
`
WebGL (2.0=true): F32 Textures: yes, F16 Textures: yes, Depth Textures: yes, Anisotropic Textures: yes, MRT: yes, Render to 32F: yes, Shader Texture LOD: yes, Texture Units: 16, Max Texture Size: 16384, Max Render Buffer Size: 16384, Max Cubemap Size: 16384
`

**Comment by movAX13h** [comment]
Sorry, I was not able to reproduce it. Your console output contains nothing suspicious. So far nobody else reported any problems ... seems to be very specific to your iMac and the browser you are using. There is really nothing in the shader code that I could identify as being problematic in regards to compatibility. You could try to run it in GL (not WebGL) in a desktop application and see if it works there. The shader has been used in FL Studio for some years now and has never been reported broken (at least to me).

**Comment by nathanvogel** [comment]
Yep, it's obviously going to be difficult if you can't reproduce what is a silent fail on my side 😟 
Just to be clear, I've seen it fail on at least three devices (1 iMac and 2 similar MacBooks) and every browser I tried on those devices (Firefox, Chrome, Safari).
I'll try to run it in GL, thanks for the tip and your time!

**Comment by nathanvogel** [comment]
I've done some testing on Shadertoy, if I comment this line of the `character` function `if (clamp(p.x, 0.0, 4.0) == p.x && clamp(p.y, 0.0, 4.0) == p.y)`, it works! 
So what makes the screen black is the character function always returning zero because the conditions are never met (neither is, I checked by using the || operand).

Of course the render is a bit glitchy, but not too bad, here's the result: https://imgur.com/a/971KMAQ

Do you have an idea what the issue could be?

**Comment by movAX13h** [comment]
Oh, great! 

That's easy to solve ... it's equivalent to 
`if (p.x >= 0.0 && p.x <= 4.0 && p.y >= 0.0 && p.y <= 4.0)`

I've updated the shader on shadertoy.
https://www.shadertoy.com/view/lssGDj

**Comment by nathanvogel** [comment]
No  I think there's something wrong with the data in `p`, because the behavior stays the same 😢

**Comment by movAX13h** [comment]
Hm... weird! Can you find out in which range it is by changing the if statement?

**Comment by nathanvogel** [comment]
Hi, sorry for the delayed answers, I don't often have access to a machine on which the bug happens.

Okaaay, there seems to be an issue with WebGL / GLSL or something like that. While doing some testing, I realized something was terribly wrong:
This evaluates to true (as expected):
```
float a = 1.0;
if (true && a == 1.0) 
```
While this evaluates to false :no_mouth::
```
float a = 1.0;
if (a == 1.0 && true) // -> false!
```

It's the case even if we use other operators like `||` or `>=    !=    <=` or an `int`, as long as there is a variable comparison followed by another condition it seems. Your vector variables are fine! (.x is always one of those for example: -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0).

So I've found this brilliant workaround:
```
    if (p.x >= 0.0) {
        if (p.x <= 4.0) {
            if (p.y >= 0.0) {
                if (p.y <= 4.0) {
                    // The same math goes here...
                }
            }	
        }
    }
```
For the record, it also works by separating the clamp() version in two ifs.
It's unlisted [here on Shadertoy](https://www.shadertoy.com/view/wdjGW3) and I'll try to make a PR on pixi-filters within a few days.

Thanks for the support @movAX13h ! 🙌

**Comment by movAX13h** [comment]
Awesome! Yes, clamp was used because I ran into the issue with multiple if-clauses back then. It's a very weird bug of early WebGL shader compilers. I never had problems with clamp though and will revert to the clamp version on shadertoy.

**Comment by nathanvogel** [comment]
Super cool! 👌Now I understand why you used clamp!
