### ISSUE TITLE
Filter types don't work properly with v5

### ISSUE THREAD

**Issue by Dairnon** [pixijs/pixi-filters#188]
No matter what way I try to import filters in typescript 

Weather it be using just the global via 

PIXI.filters.GlowFilter (using the global PIXI and script tags)
or 
import 'pixi-filters';
or
import {GlowFilter} from '@pixi/filter-glow';

I keep getting the same error issue that the filter is missing properties from type "Filter"

### Expected Behavior
For the filters to import correctly so I can add them to the filter property
### Current Behavior
TS2740: Type 'GlowFilter' is missing the following properties from type 'Filter': padding, resolution, enabled, autoFit, and 5 more.

I am using the PIXI global currently with TS

I've tried the PIXI.filters global and importing to see if I could a version working within ts
### Possible Solution
I don't really know yet.
### Environment

- **`pixi.js` version**: _e.g. 5.0.0_rc
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Windows 10
- **Running Example**: _url_

**Comment by hanesjw** [comment]
Any progress on this? I'm running into the same issue. Seems PIXI.filters is simply missing a lot of filters.

**Comment by bigtimebuddy** [comment]
Could someone provide an example/repo of this failing?

**Comment by bigtimebuddy** [comment]
Fixed by #250
