### ISSUE TITLE
Filters don't work properly in v5

### ISSUE THREAD

**Issue by Dairnon** [pixijs/pixi-filters#189]
I believe the defaults for how filters work changed since v5 
This only happens when you use a custom texture from a baseTexture (to lets say cut out a part of a texture for a sprite.

You can see the default behavior here in v4.8.5

https://www.pixiplayground.com/#/edit/NQfr8fq42KDSDJX2ITubw

and in v5.0.0-rc

https://www.pixiplayground.com/#/edit/kAH5ezneCrbQPsr6MVzt0

**Comment by ivanpopelyshev** [comment]
Default padding is now 0. Old one was 4.

**Comment by Dairnon** [comment]
Okay, we should let people know when switching to v5 that its different. 

I propose a v4 to v5 gotcha guide. 

Thanks @ivanpopelyshev
