### ISSUE TITLE
Switch Pixi reference in examples to use HTTPS

### ISSUE THREAD

**Issue by NoiSek** [pixijs/pixi-filters#19]
Change `http://s3-eu-west-1.amazonaws.com/pixi.js/dev/pixi.min.js` to `https://s3-eu-west-1.amazonaws.com/pixi.js/dev/pixi.min.js`.

This would prevent issues in situations where the github.io link is HTTPS rather than HTTP and throws a `Mixed Content` exception.

**Comment by englercj** [comment]
Should actually be switched to use the download urls:

```
https://pixijs.download/dev/pixi.min.js
```
