### ISSUE TITLE
Problem with Glitch Filter - could not initialize shader

### ISSUE THREAD

**Issue by gibbsy** [pixijs/pixi-filters#190]
I'm finding the glitch filter won't run on Dell Ultrabook win7 laptops. I have tried PIXI.settings.PRECISION_FRAGMENT = 'highp' and legacy: true but still no joy. Is there a way to test a filter for compatibility on a particular machine before attempting to render it, so it doesn't break my application? 
I should add that some of the filters run fine on these machines  (blur, glow, displacement, crt).  Thanks!
![image](https://user-images.githubusercontent.com/11939697/52786924-2f45cb00-3054-11e9-8ca6-0d73304d8b06.png)

**Comment by ivanpopelyshev** [comment]
Looks like we found the problem. Win7/Win8.1

**Comment by bigtimebuddy** [comment]
Merged fix. Closing old issue.
