### ISSUE TITLE
the fiters lib has js versions?

### ISSUE THREAD

**Issue by yyman001** [pixijs/pixi-filters#191]
i see the `kernel code ` is not `js`,
i want to lean it , i can't read the language

**Comment by bigtimebuddy** [comment]
The non-JavaScript language bits are GLSL.

**Comment by yyman001** [comment]
@bigtimebuddy Can I implement it using js?

**Comment by englercj** [comment]
GLSL is the OpenGL Shader Language. It is a language we use to write code that runs on the GPU, not the CPU. Writing it in JS isn't really an option.

**Comment by yyman001** [comment]
@englercj can i use GLSL in `node` the environment ? i need change the color color for `png`  in `node`,because i use `PIXI.js` in web.

**Comment by englercj** [comment]
I think you want something like https://www.npmjs.com/package/pngjs

**Comment by yyman001** [comment]
thank all~
