### ISSUE TITLE
Type definitions incompatible with PIXI v5 rc2 

### ISSUE THREAD

**Issue by uahic** [pixijs/pixi-filters#197]
The filter typings (types.d.ts) of 2.7.x extend from PIXI.Filter<{}> but it seems that PIXI.Filter is not generic (anymore?). Removing the brackets simply made the type checker happy.

**Comment by bigtimebuddy** [comment]
Working on it: #195

**Comment by bigtimebuddy** [comment]
Works with the latest typings. Closing.
