### ISSUE TITLE
Cannot find module 'glslify'

### ISSUE THREAD

**Issue by thiervoj** [pixijs/pixi-filters#20]
I want to use `pixi-filters` like this : 
```javascript
const PIXI = require('pixi.js'),
    filters = require('pixi-filters')
```

But when my `browserify` task is running, i get this error : 
![capture d ecran 2017-04-10 a 12 16 44](https://cloud.githubusercontent.com/assets/10621317/24857159/99243588-1de7-11e7-84cd-a23fd61bd237.png)

All my packages are up to date and correctly installed, but this one seems to have a problem with `glslify`.

How can I solve the problem ?

**Comment by englercj** [comment]
It is because it is listed as a `devDependency` but should be a `dependency` since it is a browserify loader. You can work around it by just installing glslify: `npm i -S glslify`

**Comment by thiervoj** [comment]
It works, thanks !

**Comment by bigtimebuddy** [comment]
The issue is that the package.json file lists glslify as a transform. Browserify respect this event for node_modules. This will be resolve in the next minor version when we move to Rollup instead of Browserify.
