### ISSUE TITLE
Update package on npm website

### ISSUE THREAD

**Issue by Vardner** [pixijs/pixi-filters#200]
just update for PIXI V5 support

**Comment by Genroa** [comment]
That would be really helpful. A lot of people use the v5 version of PIXI, but this package is completely unusable for now (unless you build it yourself, seeing the state of the master branch?). Is there a release date planned for the v5 compatible release of this package? :)

**Comment by nchase** [comment]
I think this is fixed @Vardner @Genroa

**Comment by bigtimebuddy** [comment]
You’re right, did the v5 release for filters.
