### ISSUE TITLE
DropShadowFilter no longer working as expected in v5

### ISSUE THREAD

**Issue by JohnKarel** [pixijs/pixi-filters#203]
Hi

Previously, in v4, DropShadowFilter distance worked as expected.
In v5, the distance behaves differently.

You can try it out in my pixiplayground example here:
https://pixiplayground.com/#/edit/auBW0tG~G4HDjiWmOwegk

Thanks in advance
Kind regards

**Comment by JohnKarel** [comment]
Thanks for classifying as bug; any idea on ETA for a fix?

**Comment by bigtimebuddy** [comment]
No idea about when a fix will be available, right now we're working on getting v5 out the door, then we'll focus on all the plugin issues, like this one. 

Welcome a PR fix if anyone wants to take a crack at it!

**Comment by ivanpopelyshev** [comment]
Got it. DropShadow was hackity-hack I dont even remember who made it.

@JohnKarel if it doesnt show on some older devices, please adjust its quality. I remember we had a problem with number of samples per

I also have better version of Blur/DropShadow/Glow that i'll publish this month :)

**Comment by jdelrue** [comment]
Cool stuff Ivan thanks!

**Comment by bigtimebuddy** [comment]
Fixed in latest release.
