### ISSUE TITLE
How to use colorMapFilter for 512x512 lut image

### ISSUE THREAD

**Issue by evanyuanvip** [pixijs/pixi-filters#205]
like this:
![front_cx](https://user-images.githubusercontent.com/6177305/57499676-242ccf00-7313-11e9-837f-875607275455.png)

**Comment by ivanpopelyshev** [comment]
Take https://github.com/pixijs/pixi-filters/blob/master/filters/color-map/src/ColorMapFilter.js 

Here's fragment shader: https://github.com/pixijs/pixi-filters/blob/master/filters/color-map/src/color-map.frag 

Here's vertex shader: https://github.com/pixijs/pixi-filters/blob/master/tools/fragments/default.vert

Combine it all , change the params/algorithm you need, and it'll work.

Filter is `PIXI.Filter`

Texture is `PIXI.Texture`

I hope that's enough for you to make your own filter based on that ColorMap

**Comment by evanyuanvip** [comment]
Thank you, I have already got it.

**Comment by jiseopX** [comment]
> Thank you, I have already got it.
@evanyuanvip 
can you tell me how you did implemented ?
