### ISSUE TITLE
NPM install doesn't works because of filter-radial-blur dependency

### ISSUE THREAD

**Issue by sermmor** [pixijs/pixi-filters#210]
Hello. I try to install pixi-filters by npm with the terminal sentence:
`npm install pixi-filters`
But it cause the following error output:
`npm ERR! code ETARGET
npm ERR! notarget No matching version found for @pixi/filter-radial-blur@^3.0.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'pixi-filters'
npm ERR! notarget`

I don't have any idea about what it's happening, but it seems like version 3.0.1 of filter-radial-blur doesn't found in npm. In fact, if I install filter-radial-blur, using npm, npm installs the 2.7.0 version of filter-radial-blur.

Please, ¿could you help me to install pixi-filters?

**NOTE:** I'm using Pixi v5.0.0.

**Comment by bigtimebuddy** [comment]
I cannot reproduce this. When I do a clean `npm install pixi-filters` I get this response:

```
+ pixi-filters@3.0.2
added 48 packages from 17 contributors and audited 1205 packages in 5.29s
```

**Comment by sermmor** [comment]
Allright. I created a empthy folder with only my package.json and package-lock.json and I did `npm install` and then `npm install pixi-filters` and it installed fine. I've copied the node_modules folder to my project and it's working fine.

Thanks a lot!
