### ISSUE TITLE
o.hex2rgb is not a function

### ISSUE THREAD

**Issue by globules-io** [pixijs/pixi-filters#211]
Trying to add DropShadowFilter with PixiJS 5.0.3 + pixi-filters v3.0.1 (3.0.2 does not have release code, just source code).

**Getting error o.hex2rgb is not a function**

           var shadow = new PIXI.filters.DropShadowFilter();            
           shadow.color = 0x000000;

**Comment by bigtimebuddy** [comment]
Please provide more information or an example. Are you in a web-browser or using a bundler like Webpack or Rollup. If so, which?

**Comment by globules-io** [comment]
I am in Chrome, using [production build 5.0.3](https://pixijs.download/v5.0.3/pixi.min.js) I suppose this is ES5 (?)

        var pixi = new PIXI.Application({width:414, height:736, transparent:true, resolution:1});
        $('#pixi')[0].appendChild(pixi.view);       
        pixi.loader.add('texture', 'img/data.json');
        pixi.loader.load(function(loader, resources){
            shadow = new PIXI.filters.DropShadowFilter();            
            shadow.color = 0x000000;
       });

**Comment by bigtimebuddy** [comment]
Yup, I can reproduce this:
https://jsfiddle.net/bigtimebuddy/03yuwedx/

Will look into it.

**Comment by bigtimebuddy** [comment]
This build should work:
https://filters.pixijs.download/latest/pixi-filters.js

Fixed:
https://jsfiddle.net/bigtimebuddy/03yuwedx/2/

**Comment by globules-io** [comment]
Yup that works, thanks for the fix.
