### ISSUE TITLE
DropShadowFilter causing pixelation of graphics edge

### ISSUE THREAD

**Issue by gparvind** [pixijs/pixi-filters#215]
Using pixijs 5.0.4 (from pixijs.download/dev/pixi.js) and pixi-filters 3.0.3.

Drawing a circle on graphics. But the moment I add a DropShadowFilter, the circle edge becomes pixelated.

<img src="https://user-images.githubusercontent.com/1861655/60392520-6e1b7f80-9b22-11e9-8f6d-948a1deb77c8.png" width="200px"/>
<img src="https://user-images.githubusercontent.com/1861655/60392527-84c1d680-9b22-11e9-86ca-12c5f98e2984.png" width="200px"/>

Code snippet:

application initialization:

```
var app = new PIXI.Application({
    view: canvas,
    antialias: true,
    width: 1000,
    height: 1000,
    autoDensity: true,
    backgroundColor: 0xf0fff0,
    resolution: devicePixelRatio,
});
```

graphics object:

```
var gc = new PIXI.Graphics();
gc.beginFill(0xf0f0a0, 1);
gc.drawCircle(0, 0, 50);
gc.endFill();
```

dropshadow filter:

```
var dropShadowFilter = new PIXI.filters.DropShadowFilter();
dropShadowFilter.color = 0x000020;
dropShadowFilter.alpha = 0.5;
dropShadowFilter.blur = 0;
dropShadowFilter.distance = 5;
dropShadowFilter.quality = 3;
gc.filters = [dropShadowFilter];

```

Any idea what could be wrong?

**Comment by karutt** [comment]
I have the same problem. I asked the question in stackoverflow, but it has not been resolved.
[>> Antialias does not work when applying drop shadow filter in pixi.js](https://stackoverflow.com/questions/56891241/antialias-does-not-work-when-applying-drop-shadow-filter-in-pixi-js)

**Comment by gparvind** [comment]
Setting filter.resolution to say 5 fixes this but I think it should be handle better with the default resolution itself. Will let the authors comment on this.

**Comment by bigtimebuddy** [comment]
This is a limitation of rendering Graphics in PixiJS. Antialias is not supported for Graphics when filters are applied. You can, as people suggested here, change the resolution. Another approach is to set multisampling and render to a RenderTexture. Here's an example:

https://jsfiddle.net/bigtimebuddy/db2ns8o4/
