### ISSUE TITLE
[BUG] Zoom Blur Filter doesn't work on Safari

### ISSUE THREAD

**Issue by panjikharisma** [pixijs/pixi-filters#216]
Hi, I have tried the Zoom Blur Filter on the demo page using Safari 12.1.1 (https://pixijs.io/pixi-filters/tools/demo/), however it doesn't show the result as it should be.

Here is the comparison with Firefox & Chrome: https://imgur.com/a/Un0nsnb

Thanks.

**Comment by wversluys** [comment]
Hi,

Is there any update regarding this issue? I would really like to use this filter, but as it stands now it's not an option.

**Comment by wversluys** [comment]
Alright.. I have a small update for this issue.. it seems the value MAX_KERNEL_SIZE of 32.0 is too big for iOS. So my guess is it won't do the final loop and always returns the vec4(0.0) (which is black).

To make the ZoomBlur visible on iOS devices, make sure the MAX_KERNEL_SIZE does not go above 13.0 (not sure yet if this is the max value for older phones (testen on iPhone 8)). The ZoomBlur filter does show some dithering though.

As for the Safari issue on OSX, the filter still looks different. Adjusting the MAX_KERNEL_SIZE does change it's appearance slightly, but never generates the same blur effect as in other browsers.

**Comment by bigtimebuddy** [comment]
I added `maxKernelSize` to the ZoomBlurFilter options which can be used to lower this for other environments. I decided to keep the default `32` to be backward compatible. Maybe in the future we can lower to support older platforms. Thanks for figuring this out @wversluys.
