### ISSUE TITLE
GlowFilter looks buggy in some cases.

### ISSUE THREAD

**Issue by nulld** [pixijs/pixi-filters#217]
I'm trying to pick parameters to make glow filter looks exactly like in flash. 

`new GlowFilter(0xede508, 1, 20, 20, 2)` (color=0xede508, alpha=1, blurX=20, blurY=20, strength, quality=1, inner=false, knockout=false)

My PIXI version becomes like this: `return new PIXI.filters.GlowFilter(20, 2, 0, 0xede508);`
but as you can see on the attached screenshot, ugly sharp edges appears.

Will really appreciate for any hints how to fix it.

![image](https://user-images.githubusercontent.com/2820168/60922290-0d6c0f80-a2a5-11e9-8800-2ba849cfb6bb.png)

code to reproduce an issue:
```
const app = new PIXI.Application({width:300, height:300, forceCanvas: false, antialias: true, transparent:true});
app.renderer.autoResize = true;

PIXI.loader
  .add("assets/gui/Popups/POPUP_window_border.png")
  .add("assets/popups/skin.jpg")
  .load(setup);

function setup() {
    let texture = PIXI.utils.TextureCache["assets/gui/Popups/POPUP_window_border.png"];
    const border = new PIXI.Sprite(texture);
    border.x = 100;
    border.y = 100;

    const bg = new PIXI.TilingSprite(
        PIXI.utils.TextureCache["assets/popups/skin.jpg"],
        app.screen.width,
        app.screen.height,
    );

    app.stage.addChild(bg);
    app.stage.addChild(border);

    border.filters = [new PIXI.filters.GlowFilter(20, 2, 0, 0xede508)];
}
document.body.appendChild(app.view);
```

assets:
![POPUP_window_border](https://user-images.githubusercontent.com/2820168/60922521-9d11be00-a2a5-11e9-840c-379c66b601ed.png)
![skin](https://user-images.githubusercontent.com/2820168/60922556-ae5aca80-a2a5-11e9-9cf1-2bdb75b429ea.jpg)

**Comment by djmisterjon** [comment]
you sure it not a padding issue ?
`f = new PIXI.filters.GlowFilter(20, 2, 0, 0xede508)`
`f.padding = 999;`

**Comment by nulld** [comment]
Thanks! looks better now. But not as saturate as flash version. Will work on it.
![image](https://user-images.githubusercontent.com/2820168/60964539-409db580-a31c-11e9-88db-75cc3259bf8b.png)

**Comment by nulld** [comment]
Seems that setting padding by filter itself will make api more clear and userfriendly. Any reason why not to do that way?

**Comment by laino** [comment]
@nulld The glow filter has some problems with how it handled certain color values.

You can try this version which also automatically sets padding:

https://github.com/pixijs/pixi-filters/pull/239

**Comment by bigtimebuddy** [comment]
Padding is now automatically handled by the constructor setting distance.
