### ISSUE TITLE
How can I animate the CRT filter?

### ISSUE THREAD

**Issue by superfunkminister** [pixijs/pixi-filters#219]
Hey! How can I animate the CRT filter as seen in the [demo](http://pixijs.io/pixi-filters/tools/demo/)? I tried updating the provided values within a Ticker loop but couldn't replicate the wavy lines...

**Comment by bigtimebuddy** [comment]
[Here](https://github.com/pixijs/pixi-filters/blob/master/tools/demo/src/filters/crt.js#L21-L26) is how the demo does it. Basically, increment the time and randomize the seed (for noise).

**Comment by superfunkminister** [comment]
Awesome, thanks!
