### ISSUE TITLE
No filters are working on the demo page

### ISSUE THREAD

**Issue by MartDSam** [pixijs/pixi-filters#220]
I have a localhost project that works normally, but the demo site is not applying any filters. Simply nothing happens, and neither of the error in the console.

[http://pixijs.io/pixi-filters/tools/demo/](http://pixijs.io/pixi-filters/tools/demo/)

**Comment by bigtimebuddy** [comment]
Yup, this is a bug with **dev**

**Comment by bigtimebuddy** [comment]
This is fixed now.
