### ISSUE TITLE
Dropshadow not showing original sprite (even with shadowOnly: false)

### ISSUE THREAD

**Issue by wellcaffeinated** [pixijs/pixi-filters#222]
I'm not sure what's going on. I've got a few layers, and have added a basic drop shadow filter to one of the layers, but it only shows the drop shadows, not the original sprites.

Here's the code:
https://github.com/minutelabsio/flight-speed/blob/master/src/components/flight-speed-canvas.vue#L192

Here's the test page:
https://labs.minutelabs.io/flight-speed/#/

Do you have any idea what might be causing this issue?

version: 3.0.3

**Comment by djmisterjon** [comment]
did you sure you not set `shadowOnly=true` somewhere ?
![image](https://user-images.githubusercontent.com/24865815/66612319-6cd10880-eb8f-11e9-85ad-b36541569d6e.png)

**Comment by wellcaffeinated** [comment]
The line of code I linked to above is the only time i touch the filter, and i specifically set it to false

thanks

**Comment by wellcaffeinated** [comment]
This is from my code after i initialize:

![image](https://user-images.githubusercontent.com/1128935/66614731-5c1c9480-eb87-11e9-81c8-7b69acbfb886.png)

**Comment by djmisterjon** [comment]
hum ok, if you don't get other theory from others, feel free to make a `pixiplayground` near your context code, i can help you to try debug your issue.
https://www.pixiplayground.com/

**Comment by wellcaffeinated** [comment]
I don't know what happened, but i think it's a webpack compile bug.

To solve this I did the following:
1. yarn remove @pixi/filter-drop-shadow
2. yarn add pixi-filters
3. rm -rf node_modules
4. rm yarn.lock
5. yarn install

Now it works somehow...
