### ISSUE TITLE
Bevel filter (secretly) relies on "alpha-padding" to detect edges

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi-filters#230]
`@pixi/filter-bevel` relies on alpha to detect the "shadow" & "light" boundaries.

```js
float light = texture2D(uSampler, vTextureCoord - transform).a;
float shadow = texture2D(uSampler, vTextureCoord + transform).a;

color.rgb = mix(color.rgb, lightColor, clamp((color.a - light) * lightAlpha, 0.0, 1.0));
color.rgb = mix(color.rgb, shadowColor, clamp((color.a - shadow) * shadowAlpha, 0.0, 1.0));
```

Hence, the bevel filter applies correctly only if there is at least a single-pixel padding with alpha=0 around an image.

If you don't do that, the bevel filter will not apply on the left & top sides of the image because there is no padding given to the object in the render-texture.

![image](https://user-images.githubusercontent.com/22450567/68436505-34234f80-018c-11ea-8652-445782e72b81.png)

To solve this problem, a padding of 1 put on the filter should suffice. In fact, doing so from "outside" solves the problem.

```js
const b = new BevelFilter(options)
b.padding = 1
return b
```

![image](https://user-images.githubusercontent.com/22450567/68436782-fbd04100-018c-11ea-8fc7-c6a12c9c9eba.png)

**Comment by mhsdevus** [comment]
+1 and thanks to @SukantPal for the workaround.

**Comment by bigtimebuddy** [comment]
Confirmed: 
https://jsfiddle.net/bigtimebuddy/1bcfy9vd/
