### ISSUE TITLE
GodrayFilter does not work with default config

### ISSUE THREAD

**Issue by Metatron92** [pixijs/pixi-filters#232]
Hello

GodrayFilter does not work.
Javascript warning: 

> Uncaught TypeError: Cannot set property 'dimensions' of undefined

Playground link: [https://www.pixiplayground.com/#/edit/iuojVuHNaVBJa8BrrBNOt](url)

**Tested on** Windows 10
Google chrome version 78

**Comment by bigtimebuddy** [comment]
Unable to reproduce error: 
https://jsfiddle.net/bigtimebuddy/kv2gc76a/
