### ISSUE TITLE
Trying to get a working setup with static types without using a bundler.

### ISSUE THREAD

**Issue by raphaelsantos** [pixijs/pixi-filters#249]
I have this small lab project that I've been managing to work locally without using a bundler. My index.html is importing pixi from CDN and the type definitions are coming from node_modules (I added "pixi.js" to "types" in my tsconfig, so I get static typing).
 
It was all looking good till I tried adding pixi-filters into the equation. I'm also adding it to my html through CDN and installing it via NPM, and added "pixi-filters" to my tsconfig. It seems to work in part, but for some reason the types do not match the code. For example in the type definition for "AdvancedBloomFilter" has no namespace, but in the actual code it is PIXI.filters.AdvancedBloomFilter 😮.

Is it possible to get a working setup without having to use a bundler? 

Thanks in advance.

**Comment by bigtimebuddy** [comment]
We should probably support the `PIXI.filters` namespace here, like we do in `pixi.js`. I had assumed not many people would types without bundling. Sorry about that!

Not ideal, but I put together a workaround example. Particularly see the `typings/global.d.ts` for how the `pixi-filters` are exported into `PIXI.filters`.

https://github.com/bigtimebuddy/pixi-filters-typescript-example

**Comment by raphaelsantos** [comment]
Thank you very much for the quick answer and for taking the time to set up an example! 

This workaround helps already. I'll come back with news if I find a way to export all classes at once. Thanks again!

**Comment by bigtimebuddy** [comment]
Yeah, no problem. If you find a better solution, let me know and I’ll add it to the project. I’d need to do the same thing internally too. Adding all exports to a namespace.

**Comment by bigtimebuddy** [comment]
@raphaelsantos I updated the project link above to support pixi-filters@3.1.1, which now supports the global namespace if you're using ambient types. Much better! Thanks for point out the issue.

**Comment by danieletulone** [comment]
Hi, I'm using webpack and I'm using new version of pixi-filter.
I fix that using webpack externals (to indicates how to resolve external dependencies)

```javascript

externals = [
  { 'pixi.js': 'PIXI' },
  function (context, request, callback) {
    // all @pixi/filter- and pixi-filters from PIXI.filters
    if (request.startsWith('@pixi/filter-')) {
      return callback(null, 'PIXI.filters')
    }
    
    // @pixi/core, @pixi/display, etc.
    if (/^@pixi\/(?:.*)$/.test(request)) {
        return callback(null, 'PIXI')
     }
     
     // IMPORTANT: webpack require this call to continue build process.
     callback()
  }
]

```
