### ISSUE TITLE
Deprecation warnings on latest dev build of pixi

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi-filters#251]
```
PixiJS Deprecation Warning: Use CLEAR_MODES when using clear applyFilter optionDeprecated since v5.2.1
```
Due to the boolean value in the 4th parameter of the 'apply' function being deprecated in `bindAndClear` in `FilterSystem`
```
if (typeof clearMode === 'boolean')
{
    clearMode = clearMode ? CLEAR_MODES.CLEAR : CLEAR_MODES.BLEND;
    // get deprecation function from utils
    deprecation('5.2.1', 'Use CLEAR_MODES when using clear applyFilter option');
}
```

**AdvancedBloomFilter**
this._extractFilter.apply(filterManager, input, brightTarget, **true**, currentState);
this._blurFilter.apply(filterManager, brightTarget, bloomTarget, **true**, currentState);

**DropShadowFilter**
this._tintFilter.apply(filterManager, input, target, **true**);
this._blurFilter.apply(filterManager, target, output, **clear**);

**Comment by bigtimebuddy** [comment]
Good call. I’ll fix these
