### ISSUE TITLE
Godray filter lacks alpha support

### ISSUE THREAD

**Issue by jrod-disco** [pixijs/pixi-filters#262]
Not sure if this issue has been brought up before but it would be nice for the `godray` filter to support alpha like some of the other filters.

`godrayInstance.alpha=0` would render only the rays themselves invisible
`godrayInstance.alpha=1` would render the rays fully visible
(and every float in between)

I've actually got a branch with this working locally and would gladly submit a clean PR if that's an option.

Cheers.

**Comment by bigtimebuddy** [comment]
Yes, PR welcome!

**Comment by jrod-disco** [comment]
@bigtimebuddy up and ready - let me know if there's anything you'd like me to tweak

**Comment by ivanpopelyshev** [comment]
Godray is better to use as mesh-shader. Just convert it to shader https://pixijs.io/examples/#/mesh-and-shaders/triangle-color.js and put a mesh on screen.

**Comment by bigtimebuddy** [comment]
Merged.
