### ISSUE TITLE
Some style adjustment suggestions

### ISSUE THREAD

**Issue by lvfangren** [pixijs/pixi-filters#264]
Some style adjustment suggestions

https://pixijs.io/pixi-filters/tools/demo/

![image](https://user-images.githubusercontent.com/25928863/84799100-56d4eb00-b02e-11ea-90d3-433fb7c49ded.png)

[question]The problem is that the drop-down box on the right clicks and there is an exception in the drop-down, which causes other drop-down options to be hidden

[solution]  overflow-y:auto; attribute can be added to the #container element

[question] Is it possible to make the width of the child li and the width of the parent element the same, because the width is inconsistent I will feel very strange

[solution]  I think you can remove the border-left attribute value of the father li element

[question] Let the control area on the right stick to the far right

[solution] Let the right value of the logo element be 0px, .dg.a element margin-right delete

I will get a 404 error when I run npm run examples locally, so I cannot preview and submit pr locally

**Comment by bigtimebuddy** [comment]
These are issues having to do with [dat.gui](https://github.com/dataarts/dat.gui). We can override some things, but the base CSS id handled there.

**Comment by bigtimebuddy** [comment]
Do run examples locally you can run these three processes. Will add a convenience method for doing them at once.
```
npm run watch:tools
```
```
npm run watch
```
```
npm run demo
```

**Comment by bigtimebuddy** [comment]
Simplifies running demo with 5379536
