### ISSUE TITLE
Twist Filter doesn't work with Pixi 5 or I'm wrong

### ISSUE THREAD

**Issue by sndrgb** [pixijs/pixi-filters#267]
Hi guys, I'm trying to use Twist Filter with Pixi 5 but I think something is broken.

Maybe the filterArea uniform? I don't understand why, can someone help me?

**Comment by bigtimebuddy** [comment]
Here's an example.

https://jsfiddle.net/bigtimebuddy/omfy3w9d/

Try setting the `offset` property to a point the center of the Twist.
