### ISSUE TITLE
ConvolutionFilter - how does it work?

### ISSUE THREAD

**Issue by jnsmalm** [pixijs/pixi-filters#271]
It says I should give it a matrix (array length 9) - but how do I know which numbers to put into that array? Where can I learn more?

**Comment by jnsmalm** [comment]
Figured it out by reading https://docs.gimp.org/2.10/en/gimp-filter-convolution-matrix.html

**Comment by bigtimebuddy** [comment]
The doc link got gimp is out of day. This would be great to fix in the docs.
