### ISSUE TITLE
AdvancedBloomFilter, BloomFilter, and DropShadowFilter use incorrect resolution setting

### ISSUE THREAD

**Issue by dev7355608** [pixijs/pixi-filters#273]
The default argument of `resolution` in the constructors of `AdvancedBloomFilter`, `BloomFilter`, and `DropShadowFilter` is currently `settings.RESOLUTION`, but it should be `settings.FILTER_RESOLUTION`.

**Comment by bigtimebuddy** [comment]
Good catch. PR welcome to fix this.
