### ISSUE TITLE
Color Overlay Opacity

### ISSUE THREAD

**Issue by gregmax17** [pixijs/pixi-filters#286]
Is there a way to add an opacity to the Color Overlay filter? Where it stands right now, it's just a solid color.

**Comment by bigtimebuddy** [comment]
It does not exist, but we'd welcome a PR to add it!

**Comment by bigtimebuddy** [comment]
At least sure it's builds `npm run build` successfully. All the commands (build, lint, etc) will get run when you submit the PR.

**Comment by gregmax17** [comment]
It gets stuck here:

```lerna notice cli v3.13.4
lerna info filter [ '@tools/*' ]
lerna info Executing command in 2 packages: "npm run build"
lerna info run Ran npm script 'build' in '@tools/demo' in 6.8s:

> @tools/demo@4.0.0 prebuild /Users/gregoryathons/Documents/Sourcetree/_Me/pixi-filters/tools/demo
> rimraf index.js.map index.js


> @tools/demo@4.0.0 build /Users/gregoryathons/Documents/Sourcetree/_Me/pixi-filters/tools/demo
> cross-env NODE_ENV=production rollup -c```

**Comment by bigtimebuddy** [comment]
Would you mind committing your changes to your fork? I can help you debug this, sure it's something simple.

**Comment by gregmax17** [comment]
ok, committed [here](https://github.com/gregmax17/pixi-filters)

**Comment by gregmax17** [comment]
@bigtimebuddy did you get a chance to look at it, did I do it properly?

**Comment by bigtimebuddy** [comment]
You did! I was able to get this to build and run fine. I have a few small notes, but otherwise I think this is good to add. Go ahead and make a PR for this.

**Comment by bigtimebuddy** [comment]
Merged! You can test it here: https://filters.pixijs.download/main/demo/index.html
