### ISSUE TITLE
Pixi.Filter is undefined

### ISSUE THREAD

**Issue by ulitiy** [pixijs/pixi-filters#3]
Hello! Your README approach doesn't seem to work or there's a version conflict or something.
```
  <script src="/node_modules/pixi.js/bin/pixi.js"></script>
  <script src="/node_modules/pixi-filters/bin/pixi-filters.js"></script>
```

In `PIXI.Filter.prototype` -> Uncaught TypeError: Cannot read property 'prototype' of undefined
PIXI.VERSION 3.0.10
pixi-filters 1.0.0

**Comment by Dadibom** [comment]
This is for pixi v4

**Comment by bigtimebuddy** [comment]
Yes, requires v4.
