### ISSUE TITLE
Importing pixi-filters doesn't seem to do anything

### ISSUE THREAD

**Issue by AlexLomm** [pixijs/pixi-filters#32]
I'm trying to get the filters to work, but am failing to do so.

I've imported both `pixi.js` and `pixi-filters` to no avail:

```
import 'pixi.js';
import 'pixi-filters';

// ...

const outlineFilterRed = new PIXI.filters.GlowFilter(15, 2, 1, 0xff9999, 0.5);
```

Produces the following error: 

> Property 'GlowFilter' does not exist on type 'typeof filters'.

**Package Versions:**
pixi.js: 4.5.5
pisi-filters: 2.0.0

Could you please point out what am I doing wrong?

**P.S**
This issue on stackoverflow: https://stackoverflow.com/questions/46014961/how-to-get-pixi-filters-working

**Comment by AlexLomm** [comment]
Switching to version **1.0.8** has worked as expected, it's definitely a bug

**Comment by AlexLomm** [comment]
The solution is to import every filter individually, like it's written [here](https://github.com/pixijs/pixi-filters/tree/master/filters/glow).

**Comment by bigtimebuddy** [comment]
This is still an issue. Webpack uses the ES `module` import, which does _not_ assign to the global `PIXI` object. In these environments you need to specify what you'd like to import. For instance:

This works:
```js
import * as filters from "pixi-filters";
console.log(filters);
```

This will _not_ work.
```js
import "pixi-filters";
console.log(PIXI.filters);
```

Obviously, this is wrong. It should do both like the documentation says. Will publish a fix.
