### ISSUE TITLE
Drop shadow not in CDNJS

### ISSUE THREAD

**Issue by rhernandog** [pixijs/pixi-filters#33]
Hello,

For a project I'm working now I need the CDN files but the drop shadow (only filter I need for it) is not in the CDNJS links.

https://cdnjs.com/libraries/pixi-filters/1.0.8

Also is not found in the file with all the filters:

https://cdnjs.cloudflare.com/ajax/libs/pixi-filters/1.0.8/filters.js
https://cdnjs.cloudflare.com/ajax/libs/pixi-filters/1.0.8/filters.min.js

Hopefully you can upload it.

Thanks,
Rodrigo.

**Comment by MartinKolarik** [comment]
Use can use https://www.jsdelivr.com/package/npm/@pixi/filter-drop-shadow. jsDelivr serves files directly from npm, so all other filters/future version are/will be available there too.

**Comment by rhernandog** [comment]
Sweet!!! thanks @MartinKolarik 
They have the latest version. Closing.
