### ISSUE TITLE
About outline filter

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#37]
When the thickness is big , the result is strange :  
![2017-09-11 11 38 29](https://user-images.githubusercontent.com/288367/30283416-afbe76d6-96dd-11e7-935d-53fe81a452a1.jpg)

Is it a bug ?

**Comment by bigtimebuddy** [comment]
No, it's a limitation of how the OutlineFilter was implemented

**Comment by finscn** [comment]
Is there a better way to implement outline ?

**Comment by ivanpopelyshev** [comment]
Yes, do it in photoshop and change the texture instead.

**Comment by ivanpopelyshev** [comment]
I'm gonna implement that approach in runtime , much later. Working on two-tint right now.

**Comment by bigtimebuddy** [comment]
Fixed with better quality default #116
