### ISSUE TITLE
Pixelate Filter is Busted

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi-filters#4]
If you see the demos, the PixelateFilter doesn't appear to be operating correctly. Shows up as a solid block instead of pixelated image. http://pixijs.github.io/pixi-filters/examples/

**Comment by kaestel** [comment]
Hi!
I'd love to use your pixelate filter for PIXI, but it doesn't work. Either it shows a solid block - or maybe it displaces the element out of view? I can't tell if it is one or the other. It doesn't give the pixelate effect anyhow.

Do you have any fix ready or would you be able to help us fix it?

Martin

**Comment by jeff-gold-marblemedia** [comment]
does anyone have a fix for the pixelate filter? really want to use this in a project.

**Comment by jeff-gold-marblemedia** [comment]
i modified the Ascii filter to fix this.. you can replace the filter in filter.js with this as a quick hack
`function PixelateFilter()
{
    PIXI.Filter.call(this,
        // vertex shader
        "#define GLSLIFY 1\nattribute vec2 aVertexPosition;\nattribute vec2 aTextureCoord;\n\nuniform mat3 projectionMatrix;\n\nvarying vec2 vTextureCoord;\n\nvoid main(void)\n{\n    gl_Position = vec4((projectionMatrix * vec3(aVertexPosition, 1.0)).xy, 0.0, 1.0);\n    vTextureCoord = aTextureCoord;\n}",
        // fragment shader
        "#define GLSLIFY 1\nvarying vec2 vTextureCoord;\n\nuniform vec4 filterArea;\nuniform float pixelSize;\nuniform sampler2D uSampler;\n\nvec2 mapCoord( vec2 coord )\n{\n    coord *= filterArea.xy;\n    coord += filterArea.zw;\n\n    return coord;\n}\n\nvec2 unmapCoord( vec2 coord )\n{\n    coord -= filterArea.zw;\n    coord /= filterArea.xy;\n\n    return coord;\n}\n\nvec2 pixelate(vec2 coord, vec2 size)\n{\n    return floor( coord / size ) * size;\n}\n\nvec2 getMod(vec2 coord, vec2 size)\n{\n    return mod( coord , size) / size;\n}\n\nfloat character(float n, vec2 p)\n{\n    p = floor(p*vec2(4.0, -4.0) + 2.5);\n    if (clamp(p.x, 0.0, 4.0) == p.x && clamp(p.y, 0.0, 4.0) == p.y)\n    {\n        if (int(mod(n/exp2(p.x + 5.0*p.y), 2.0)) == 1) return 1.0;\n    }\n    return 0.0;\n}\n\nvoid main()\n{\n    vec2 coord = mapCoord(vTextureCoord);\n\n    // get the rounded color..\n    vec2 pixCoord = pixelate(coord, vec2(pixelSize));\n    pixCoord = unmapCoord(pixCoord);\n\n    vec4 color = texture2D(uSampler, pixCoord);\n\n    // determine the character to use\n    float gray = (color.r + color.g + color.b) / 3.0;\n\n    float n =  65536.0;             // .\n    if (gray > 0.2) n = 65600.0;    // :\n    if (gray > 0.3) n = 332772.0;   // *\n    if (gray > 0.4) n = 15255086.0; // o\n    if (gray > 0.5) n = 23385164.0; // &\n    if (gray > 0.6) n = 15252014.0; // 8\n    if (gray > 0.7) n = 13199452.0; // @\n    if (gray > 0.8) n = 11512810.0; // #\n\n    // get the mod..\n    vec2 modd = getMod(coord, vec2(pixelSize));\n\n    gl_FragColor = color;\n\n}"
    );
    this.pixelSize = 4;
}


PixelateFilter.prototype = Object.create(PIXI.Filter.prototype);
PixelateFilter.prototype.constructor = PixelateFilter;
module.exports = PixelateFilter;

Object.defineProperties(PixelateFilter.prototype, {
    /**
     * This a point that describes the size of the blocks.
     * x is the width of the block and y is the height.
     *
     * @member {PIXI.Point}
     * @memberof PIXI.filters.PixelateFilter#
     */
    pixelSize: {
        get: function ()
        {
            return this.uniforms.pixelSize;
        },
        set: function (value)
        {
            this.uniforms.pixelSize = value;
        }
    }
});

},{}],9:[function(require,module,exports){`

**Comment by KIvanow** [comment]
@jeff-gold-marblemedia , you sir, are awesome. Thank you for the quick fix on the pixelate filter

**Comment by bigtimebuddy** [comment]
@jeff-gold-marblemedia would welcome a Pull request if you could put something together.

**Comment by nchase** [comment]
hi maintainers, see #23 if this is something that you still want – hope to learn more about webGL and shaders in the near future.
