### ISSUE TITLE
Need to update with AlphaFilter

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#41]
see https://github.com/pixijs/pixi.js/pull/4349

**Comment by bigtimebuddy** [comment]
Do you mean update the demo?

**Comment by finscn** [comment]
No. Some filters in this repo use VoidFilter , but in new PIXI , there is no VoidFilter any more.

**Comment by bigtimebuddy** [comment]
AlphaFilter needs to be released first on pixi.js, but #42 addresses this. Thanks.
