### ISSUE TITLE
[REQUEST] Need more arguments of BloomFilter.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#43]
The BloomFilter based on Blur Filter.  There are  4 arguments in Blur Filter `strength, quality, resolution, kernelSize` 

But only strength(named blur in BloomFilter) should be set .
I hope BloomFilter could supply all  Blur Filter's arguments as optional .

They could help user to control the detail of bloom effect .

---
BTW , I hope `strength` and `blur` could become one name (bad english..., but I think you could understand me)

**Comment by bigtimebuddy** [comment]
Would welcome a PR for this.

**Comment by finscn** [comment]
done with #44
