### ISSUE TITLE
A different (maybe better) algorithm of Bloom Filter

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#46]
I create  a Bloom Filter : https://github.com/finscn/pixi.js/blob/master/src/morefilters/bloom/BloomBrightnessFilter.js

The algorithm learned form  https://learnopengl.com/#!Advanced-Lighting/Bloom 

I test it and PIXI's Bloom Filter,  the effect of BloomBrightnessFilter is better.

PIXI's Bloom Filter is faster ,  opengl's Bloom is better(but need more computation) . 
So I hope PIXI could support both bloom filters.

**Comment by GoodBoyDigital** [comment]
sounds cool @finscn ! Do you have an example of it in action?

**Comment by finscn** [comment]
![image](https://user-images.githubusercontent.com/288367/31331310-66a7ad0c-aca7-11e7-8d44-50e593a41e6d.png)

There is a comparison (just image).

**Comment by finscn** [comment]
But I'm very weak at Shader . So my implement is very terrible maybe.
I hope the experts of PIXI core team could re-implement with that opengl algorithm https://learnopengl.com/#!Advanced-Lighting/Bloom

**Comment by GoodBoyDigital** [comment]
that looks awesome :D

**Comment by finscn** [comment]
I found the reference of my shader :   https://qiita.com/edo_m18/items/c43177c0a18a2ea210b6

It's a Japanese article , but the source code is very easy to understand.

**Comment by finscn** [comment]
done
