### ISSUE TITLE
How to make my filter support `import fragment from './xxxx.frag'`

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#49]
I found in this repo , use `import fragment from './xxxx.frag'` to include a shader file.
But in pixi.js, don't support this way.

How to make my filter support `import fragment from './xxxx.frag'` ?

**Comment by bigtimebuddy** [comment]
Because this build process is using Rollup, which supports importing random text string likes this.

**Comment by finscn** [comment]
And pixi.js use 
```
import { readFileSync } from 'fs';

readFileSync(...)
```

I hope  pixi.js & pixi-filterd could use the same way.

**Comment by bigtimebuddy** [comment]
In the future I'm moving PixiJS to use Rollup to build instead of Browserify.

**Comment by ivanpopelyshev** [comment]
Just use multiline and embed it in js file. I'm sure you'll need templates and modifications in those lines anyway.
