### ISSUE TITLE
when use DisplacementFilter & ColorMatrixFilter , there is a strange thing.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#52]
open http://pixijs.github.io/pixi-filters/examples/ 

First , enable the DisplacementFilter, it's already enabled by default.

Then enable the ColorMatrixFilter,  you will find the  strange thing.

I don't know how to describe the thing.

Please try it by yourself.

**Comment by bigtimebuddy** [comment]
It seems likes it messes with the offset of the displacement texture and everything shifts over. Not sure why that's happening.

**Comment by ivanpopelyshev** [comment]
Yep, that's a bug.

**Comment by finscn** [comment]
In last version , this bug has disappeared... Is there anyone fix it ?

**Comment by finscn** [comment]
When use another filter(some , not all)  with DisplacementFilter , the ratio in `DisplacementFilter.applyFilter` will changed : 
```
    apply(filterManager, input, output)
    {
        const ratio =  (1 / output.destinationFrame.width) * (output.size.width / input.size.width);

        this.uniforms.filterMatrix = filterManager.calculateSpriteMatrix(this.maskMatrix, this.maskSprite);
        this.uniforms.scale.x = this.scale.x * ratio;
        this.uniforms.scale.y = this.scale.y * ratio;

         // draw the filter...
        filterManager.applyFilter(this, input, output);
    }
```

**Comment by bigtimebuddy** [comment]
Merged fix
