### ISSUE TITLE
[BUG: ShockwaveFilter] When canvas isn't a square , the wave is not a circle.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#55]
I think the code for computing `dist` has bug.

**Comment by bigtimebuddy** [comment]
I don't know what you mean. Can you try explaining or showing?

**Comment by finscn** [comment]
The shape of shockwave is not always a circle.

<img width="1031" alt="2017-10-12 7 00 25" src="https://user-images.githubusercontent.com/288367/31492946-bbfca290-af12-11e7-88bb-cdbe77648a94.png">
<img width="431" alt="2017-10-12 7 00 18" src="https://user-images.githubusercontent.com/288367/31492947-bc2d42ec-af12-11e7-82c2-0bc22bc07b83.png">

Only When the canvas is a square , The shape of shockwave is circle.

**Comment by bigtimebuddy** [comment]
I believe that's intentional.

**Comment by finscn** [comment]
Why ? 
in the real game,   what ever the game resolution ( 4:3  or 16:9 )  , the shockwave should always be a circle.

**Comment by finscn** [comment]
@bigtimebuddy  . in filter , I use this code for computing the distance of a texture-point  and `center`  :
(uCenter use  screen coord, the unit is `pixel` )
```
    vec2 center = uCenter.xy / filterArea.xy;
    vec2 dir = vec2(center - vTextureCoord);
    float dist = length(vec2(dir.x, dir.y * filterArea.y / filterArea.x));
```

**Comment by finscn** [comment]
done with https://github.com/pixijs/pixi-filters/pull/95
