### ISSUE TITLE
Talk about `ShockwaveFilter`

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#60]
My game need shockwave effect , so I have been doing research on it recently.

I think the shockwave need these features(params) : 
* center ( already in  current ShockwaveFilter, but not in pixel coord)
* time ( already in  current ShockwaveFilter)
* speed
* duration
* amplitude (  already in  current ShockwaveFilter, params.x )
* refraction ( already in  current ShockwaveFilter, params.y )
* wavelength ( already in  current ShockwaveFilter,  params.z, but not in pixel coord )
   ` Q:  params.z =  half of wavelength ??? `
* lighter

the `speed` & `duration` are very important for shockwave effect in a real game.

And the  shockwave  needs  `attenuation effect` ( bad English) . I mean that the amplitude should be smaller and smaller  with time.

the `lighter` is used for enhancing the effect. In some cases (e.g. a pond  in a dark forest) , if no lighter , player will see the shockwave effect difficulty.

---------------

So I want to create a new ShockwaveFilter, then an old question: 

Should I create a new AdvancedShockwaveFilter or create a new shockwave filter ?

Could you give me some advices please  , thank you ?

**Comment by bigtimebuddy** [comment]
If you can make this backward-compatible (i.e., don't change the defaults and add the additional parameters after the current constructor arguments), then you should try to do that.  I think these options are a great idea.

**Comment by bigtimebuddy** [comment]
"easing" might be another good property. Something simple like -1 to 1, where -1 is a bicubic ease in, and 1 is a bicubic ease out, and 0 is linear ease.
