### ISSUE TITLE
[REQUEST] A Color Adjust Filter is very useful.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#61]
I saw a color adjust Filter example : http://webglsamples.org/color-adjust/color-adjust.html
And there is a article talk about the detail of it : https://www.youtube.com/watch?v=rfQ8rKGTVlg#t=25m03s 
It's very useful for a game vfx.

Maybe we could try to include it . 

BTW , could the  ColorMatrixFilter do the same thing ?

**Comment by ivanpopelyshev** [comment]
This shader is more than simple ColorMatrixFilter: it actually maps colors through 3d texture, You also need this thing: https://github.com/hughsk/webgl-texture3d/blob/master/README.md

**Comment by bigtimebuddy** [comment]
Merged with #124

**Comment by finscn** [comment]
@bigtimebuddy  , this feature is different from #124 
#124 is just basic color adjustment , 
this request is a specific color adjustment with `3d texture`.

**Comment by finscn** [comment]
Done with #136
