### ISSUE TITLE
[REQUEST] Add some arguments to make GodrayFilter support non-parallel light.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#65]
GodrayFilter is very amazing , I love it.

But I found that some God ray effects are use non-parallel light.
e.g. 

![image](https://user-images.githubusercontent.com/288367/31573105-85896c02-b07a-11e7-8bb8-2ffc6252667b.png)
![image](https://user-images.githubusercontent.com/288367/31573107-8c5fb4dc-b07a-11e7-93ca-1b2225dde61f.png)

So Could you make GodrayFilter support non-parallel light ,please ? 
Or Should we need a new AdvancedGodrayFilter ?

**Comment by ivanpopelyshev** [comment]
You can make non-linear field here: https://github.com/pixijs/pixi-filters/blob/master/filters/godray/src/main.frag#L18

Also, non-linear fade here: https://github.com/pixijs/pixi-filters/blob/master/filters/godray/src/main.frag#L22

**Comment by finscn** [comment]
@ivanpopelyshev , thanks. But I'm not good at math , so I don't know how to modify them.
Could you give me more advices ? Thank you very much.

**Comment by finscn** [comment]
I make it be arc ... tears ...
![image](https://user-images.githubusercontent.com/288367/31577051-49bb1eac-b0cd-11e7-9f08-141c4fc21548.png)

**Comment by finscn** [comment]
![image](https://user-images.githubusercontent.com/288367/31577940-c720deea-b0dc-11e7-9df1-9903eb9878d5.png)

It's still with arc.

I've given up. I'm so stupid.

**Comment by bigtimebuddy** [comment]
I don't think arc is the right way to go, that's not really how light works, but it's getting closer. We need a way to provide an optional focal/perspective point for the rays. If the point isn't provided, the rays should be parallel.

**Comment by finscn** [comment]
My math is as weak as my english . I can't do anything for this.  waiting for @ivanpopelyshev .

I know I've wrote some filters . 
But the filters I wrote is not difficult in math, there is no any complex mathematical formulae in them.

**Comment by bigtimebuddy** [comment]
This would be nice to have, but it's lower priority. There are some other useful filters that would be worth getting in before this, like a better outline, radius blur, etc.

**Comment by bigtimebuddy** [comment]
Merged
