### ISSUE TITLE
[REQUEST] Motion Blur Filter

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#69]
I think the motion-blur is very useful.

like the blur effect of background in this  gif
![gif](https://i.imgur.com/UkJvWnc.gif)

**Comment by bigtimebuddy** [comment]
Great idea! Blurring directionally would be very useful. As would radial blur

**Comment by finscn** [comment]
But I've no idea about Blurring directionally  ... :(

**Comment by finscn** [comment]
Done with #99
