### ISSUE TITLE
[SUGGEST] Move `filters/all` & `filters/**/lib` to `dist` folder.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#76]
let the `filters` only include source code of all filters.
put the build-files to a standalone folder.

**Comment by bigtimebuddy** [comment]
Thanks for the suggestion, but this folder structure is designed for publishing multiple packages. Putting all in one folder goes against that pattern and makes it harder to publish.

**Comment by finscn** [comment]
I mean that : 
```
dist/filter-a/a.js
dist/filter-b/b.js
dist/filter-c/c.js
```
not
```
dist/a.js
dist/b.js
dist/c.js

```

**Comment by finscn** [comment]
The core of my opinion is  : 
don't leave the `all` folder in  `filters folder`.
Because  the level/category  of `all`  is not as same as other folders in `filters folder`

**Comment by finscn** [comment]
@bigtimebuddy , Could you think about it again ?
