### ISSUE TITLE
normal map GodrayFilter

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-filters#78]
Hi , first , thank you guys for **GodrayFilter** and **AdvancedBloomFilter** , your are awsome !!!
is there a chance that it can work with normal map.
idea to make fake dynamic lighting or special effects on sprites. like Emboss Effect.
if yes, do you have an example, its is simple to do?

i would like use this normal map generator
https://www.codeandweb.com/spriteilluminator
![GitHub Logo](https://cdn.codeandweb.com/img/spriteilluminator/features/si_features_normalmap_normalmap.png)
thanks

**Comment by finscn** [comment]
my fork pixi support lighting2D . you could try it , and there is a online demo : http://finscn.github.com/pixi-lights-v4/ 

but I don't understand how to use  GodrayFilter and AdvancedBloomFilter with normal map ?

**Comment by djmisterjon** [comment]
ok I guess that's not possible.
Bravos for example, I also interested in this module light.

http://proclive.io/lights-in-pixi-js/
https://englercj.github.io/2016/01/03/pixi-deferred-lighting/
