### ISSUE TITLE
npm install doesn't have any js files

### ISSUE THREAD

**Issue by shannon** [pixijs/pixi-filters#8]
When I install via npm like so:

npm install pixi-filters

I don't get any js files. Just the following:

.npmignore
package.json
README.md

Am I missing a step here?

**Comment by marekventur** [comment]
it feels like ```npm run build``` hasn't been run before publishing, could someone quickly check that?

**Comment by GoodBoyDigital** [comment]
Interesting, what do ya think @bigtimebuddy ?

**Comment by bigtimebuddy** [comment]
Confirmed this is an bug with releasing. Should be an easy fix.

**Comment by shannon** [comment]
Could use a prepublish script in package.json?

**Comment by shannon** [comment]
Sorry I didn't mean that last comment to sound short. I was replying quickly while managing some other tasks. Is the only thing that needs to be run `npm run build`? 

If so adding `"prepublish": "npm run build"` to the package.json would mean you don't have to worry about it next time.

**Comment by bigtimebuddy** [comment]
Fixed in v1.0.6 release.

**Comment by marekventur** [comment]
thanks!

**Comment by shannon** [comment]
Thanks everyone :-)
