### ISSUE TITLE
[SUGGEST] Add `list of files modified` to Wiki

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#80]
When I create a new filter , I need to modify some files.
But I often forget someone.

So, suggest add a clear list of the files need to modified.
```
	modified:   filters/all/src/index.js
	modified:   filters/all/package.json
	modified:   filters/all/types.d.ts
	modified:   filters/all/README.md
	modified:   examples/index.html
	modified:   tools/screenshots/config.json
	modified:   README.md
```

**Comment by bigtimebuddy** [comment]
We should add this to the wiki for adding new filters.

**Comment by ivanpopelyshev** [comment]
Put it in wiki )

**Comment by ivanpopelyshev** [comment]
Done, please check it. https://github.com/pixijs/pixi-filters/wiki/Adding-Filters#%EF%B8%8F--check-the-list-of-modified-global-files

**Comment by finscn** [comment]
OK.Thanks.
