### ISSUE TITLE
How to get the error log when create the screenshots ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#83]
When I run `npm run build`, if there are some errors when creating the screenshots  , I can't get them.
So

How to get the error log when create the screenshots ?
Thanks.

**Comment by bigtimebuddy** [comment]
Try “npm run build -- -d” inside screenshots

**Comment by bigtimebuddy** [comment]
```bash
cd tools/screenshots
npm run build -- --debug
```

**Comment by bigtimebuddy** [comment]
Would welcome a PR to handle errors in the Electron renderer and pass them along to console. Seems useful.
