### ISSUE TITLE
[BUG]A black rect in the center of `ShockwaveFilter` on some Android devices.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#84]
A black rect in the center of `ShockwaveFilter` on some Android devices.

When `time` become bigger , the black rect would disappear.

Android 7.0 + Samsung S7.

![image](https://user-images.githubusercontent.com/288367/31878355-6899a668-b80c-11e7-94c4-e48df65867ba.png)

there is a thread talk about it , but I don't know how to solve.

**Comment by finscn** [comment]
The black hole is not always black, sometimes there a some other color rect in it. (with different arguments)

**Comment by ivanpopelyshev** [comment]
Dont divide by zero, i guess. Center is a special case.

**Comment by finscn** [comment]
@ivanpopelyshev , I found the reason :  `normalize(dir)`.
In some platforms , if dir is vec2(0,0) , will take errors. , in some platforms , will ignore the error.
