### ISSUE TITLE
[REQUEST] The Demo uses separate filters-files when `build:dev`

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#89]
The Demo is not only for demo , it's also a very good test case.
I think many developers would use it for testing when the filter is under develop.
But  the new Demo is hard to test and dev.

When  add or modify the filters-files , users have to run `npm run build` again.

I think `uses separate filters-files` is a better choice.

Thank you.

**Comment by bigtimebuddy** [comment]
A better way to develop is by using “npm run watch” so you don’t have to rebuild every time.

**Comment by finscn** [comment]
I've tried. 
but after I changed & saved  the files of filters , reload the  demo/index.html , there is no new result.

**Comment by finscn** [comment]
I found the watch script doesn't rebuild the files for demo.

**Comment by bigtimebuddy** [comment]
Will look into it

**Comment by bigtimebuddy** [comment]
This has been fixed since I made all filters use the top-level package. You need to `npm run watch` from the root level. In another terminal instance `cd` to `tools/demo` and also run `npm run watch` there. This should allow you to change filters and change the demo.
