### ISSUE TITLE
Question - Can the Drop shadow filter render in a higher resolution   

### ISSUE THREAD

**Issue by naranjamecanica** [pixijs/pixi-filters#93]
Right now the Drop shadow filter is rendering at a 1x resolution in a 2x retina environment. Is this something that is easily fixed as a setting, like in https://github.com/pixijs/pixi-filters/pull/44? 

I've tried to recreate above pull request for the Drop shadow filter but it stays "jagged"...

**Comment by finscn** [comment]
Every filter has `resolution` property . you could do this : 
```
filter. resolution = 2;
```

**Comment by naranjamecanica** [comment]
Thanks, but I've tried that without any luck, I'll make a fiddle with my use case tomorrow.

**Comment by ivanpopelyshev** [comment]
Did you set correct resolution for renderer itself?

**Comment by bigtimebuddy** [comment]
If you could please provide a jsfiddle if these suggestions don’t work. Would be easier to figure out what’s going on.

**Comment by canonscholenprogramma** [comment]
Thanks for you fast replies, indeed in a fiddle it is working, so it must be something else in my project setup/flow. I'll figure that one out myself! 👍 

For a reference: https://jsfiddle.net/o12u0wov/34/

**Comment by naranjamecanica** [comment]
Thanks for you fast replies, indeed in a fiddle it is working, so it must be something else in my project setup/flow. I'll figure that one out myself! 👍

For a reference: https://jsfiddle.net/o12u0wov/34/

**Comment by bigtimebuddy** [comment]
`FILTER_RESOLUTION` doesn't seem to be used anywhere. It was originally added here: https://github.com/pixijs/pixi.js/commit/112bc4c4189b0269c454f0508053e41638d77ad2 and used in FilterManager. That has since been replaced. Looks like this is a vestigial property and should be removed. Anyone want to make a PR for this?

**Comment by tiye** [comment]
got some update:

```
PixiJS Deprecation Warning: settings.FILTER_RESOLUTION is deprecated, use Filter.defaultResolution
Deprecated since v7.1.0
```

https://github.com/pixijs/pixijs/pull/8865
