### ISSUE TITLE
Drop shadow filter bad performance?

### ISSUE THREAD

**Issue by Cristy94** [pixijs/pixi-filters#98]
Testing the filters here: http://pixijs.github.io/pixi-filters/examples/ most of the filters work fine at 60FPS on a laptop (i7, gtx 950M) but the drop shadow filter performance is really bad. Can the implementation of drop shadow be somehow improved?

**Comment by finscn** [comment]
I think we need a new drop shadow filter with new algorithm.
Current drop shadow filter equals to `tintFilter + blurXFilter + blurYFilter + matrix compute`.
It's so expensive.

We could move  `matrix compute` to `set/get angle`, I think.
But it's not the hotspot of performance,  `blur` is.

**Comment by Cristy94** [comment]
@ivanpopelyshev So apart from the new Matrix thing it can't be implemented more efficiently? Why do other filters work fine but the drop shadow is so heavy? Can it be done without the extra framebuffer?

**Comment by ivanpopelyshev** [comment]
Filters are using extra framebuffer. In  this case - tint+blur+blur.. oh, three extra framebuffers. It was fast in Flash, because Flash cashed stuff. Pixi doesnt do it.

We can make it without extra framebuffers - as a shader, not as a filter, but it requires time, and I dont have it.

**Comment by Cristy94** [comment]
Hmm, I thought all filters are implemented as shaders. What's the difference between shaders and filters? I didn't find anywhere a quick explanation of how the filters are implemented or any performance optimization tips for using filters.

**Comment by finscn** [comment]
BTW ,  In the example about this filter  , the filter is applied to each fish, not applied to pond , this will take the performance down.

**Comment by bigtimebuddy** [comment]
Perf PR was merged. Closing.
